NYPL-discovery/discovery-front-end

src/app/components/ItemPage/ItemPage.jsx
Add links to fields that has faceted search enabled on item page (#18)
I tested the links against the API and I think they should work.  I couldn't get the subject facet to work though: http://discovery-api.nypltech.org/api/v1/resources?q=subject:%22Globalization.%22
=> Linkify fields on item page

src/app/components/ItemPage/ItemHoldings.jsx, src/app/components/ItemPage/ItemPage.jsx, src/app/components/Results/ResultsList.jsx, src/client/styles/components/Item.scss, src/client/styles/components/Results.scss
- Create a "See (x) more items" link under bibs that have many items. 
- I added this to the search results page (limit is 5) as well as the item page (limit is 7).
- With this change, I also sorted the items based on availability, i.e. status "Available" will always be on top
- I also changed the colors for non-available items
- The implementation on the search results page is not ideal-- the sub-item list should probably be broken up into its own component, but we can refactor after the alpha is shipped if it doesn't mess anything else up
=> Collapse long lists of item under a bib item

locationCodes.js, locations.js, src/app/components/HoldPage/HoldConfirmation.jsx, src/app/components/HoldRequest/HoldRequest.jsx, src/app/utils/item.js, src/server/ApiRoutes/ApiRoutes.js
I added location-related data to the hold request and the hold confirmation pages (#24)
This includes:
- the full name of the building
- the address of the building
- the embedded map
- the hours
Some sample items for testing (e.g. `/hold/request/{id}`, and `/hold/confirmation/{id}`):
Offsite Princeton - b17667243-i22519773
Offsite - b18887197-i26265219
Schomburg - b11215031-i12061804
SASB - b18535586-i25384231
LPA - b11152464-i14946890
SIBL - b13775477-i16838667
I implemented this by hard-coding the location mappings (location codes -> location) and location data (I added embed code and hours) since there's only 4 research centers.  For the long-term implementation, this should come from the API.
Other things for future work:
- Directions to room not yet implemented
- Hours is for the …
=> Add location data to hold request and confirmation pages

src/server/routes/auth/index.js
Returning next() when oauth token fails to initialize so the app doesn't crash and can continue to make requests.
This is a server side fix. When the token expires, the browser's console will still display an error but that's from the Header which is kind of out of our control. I added a comment and suggestion regarding updating that in Kang's current [Header PR](https://bitbucket.org/NYPL/dgx-header-component/pull-requests/84/update-log-out-link/diff). Even though there's an error in the console. searching should work as expected.
=> Catch expired cookie (server-side)

src/app/components/ItemPage/ItemPage.jsx
Display all data in API response (#43)
Display call numbers correctly for holdings (#47)
Full list of data displayed:
- Title
- Type
- Language
- Date Created
- Date Published
- Contributors
- Publisher
- Place of publication
- Subjects
- Dimensions
- Issuance
- Owner
- Location
- Notes
- Bnumber
- LCCN
- OCLC Number
- OCLC Workid
=> Item page: display all data

src/app/components/ItemPage/ItemEditions.jsx, src/app/components/ItemPage/ItemPage.jsx, src/client/styles/components/Item.scss
Added related formats/editions to the item page (#17) based on workid.  
It makes an additional API call, e.g. `http://discovery-api.nypltech.org/api/v1/resources?q=idOwi:%22urn:owi:363779508%22`
If results are > 1 (excluding self), show on the bottom of the item page using the ResultsList component
=> added related formats and editions to item page based on workid

src/app/components/Hits/Hits.jsx, src/app/components/ItemPage/ItemPage.jsx, src/app/components/Results/Results.jsx
Minor formatting changes:
Search results page: Format large numbers for "hits" number
Item page: plural/singular check for "copy" / "copies"
=> Format large numbers on search results page #74

src/app/components/ItemPage/ItemPage.jsx
This PR is for issues #86 and #85.
I added the OCLC number and workid under "External Links", for now. It doesn't seem like all links to OCLC work such as the link on this page: http://dev-discovery.nypl.org/item/b18534869.
For issue #85, the LCC label is updated but the API doesn't support it right now so it's not linked.
=> Updating external links for OCLC. Updating the LCC display and search link.

.gitignore, README.md, package.json, test/Application.test.js, test/SearchButton.test.js, test/helpers/browser.js
I've used [Instanbul](https://istanbul.js.org/) before and think it's a good tool. This one, specifically the `nyc` command line tool works well with Mocha. I wrote a bit of documentation in the readme on how to run it.
The unit tests themselves may need more setting up because the components are not being checked correctly, but that's a different issue.
=> Adding nyc as the code coverage tool and setting up npm commands to run it

package.json, src/app/components/Search/Search.jsx, src/app/utils/utils.js, src/client/App.jsx, src/views/index.ejs
`Search.jsx` has an example of how the event tracking function is used. Line 23 in `App.jsx` can be uncommented to see debug statements in the console:
=> Adding the dgx-react-ga module, initializing, and tracking search key words.

package.json, src/client/styles/main.scss
I talked to kang about the alpha branches in the Header that have the logged in feature. The most current alpha branch logs you in but it shows the same logged in form without any indication that it was successful, or a redirect to the current page.
This PR has an alternate branch that logs you in and takes you to the "My Account" page in nypl-sierra-test. Besides this, the navigation links take you to a dev instance of nypl.org since it was meant to be used for user testing.
Not sure if it's going to be a problem if you try to log in through the header. If you are not logged in and you log in when placing a hold, the redirect will work and that user flow is unaffected.
Last thing, the links to the oauth endpoints are now behind a "feature flag" that triggers it. So in order to log in the …
=> Updated header login

src/app/components/FacetSidebar/FacetSidebar.jsx, src/client/styles/utils/utils.scss
The CSS rule messes up the select element on Firefox. I added it before but forgot why... I tested FF again and don't see anything apparent that messes up after removing the rule.
Also removed the visually hidden submit button for now. That causes the form to submit when an option is chosen. I think the larger discussion can be whether it should always make a fetch to the server and refresh the page, or continue with the ajax update.
=> Removing overflow hidden CSS rule from focus state.

src/app/components/Results/ResultsList.jsx, src/app/components/SearchResultsPage/SearchResultsPage.jsx, src/app/utils/item.js
- For "Request a hold" button, added "Request a hold for [title] for use in library"
- For "View online" button, added "View online resource for [title]"  (this could still use more work)
- For "See XX more items" link, added "See XX more items in collapsed menu for [title] (#114)
(Sorry, I also snuck in #106 because it was trivial change)
=> More descriptive labels for calls-to-action for screen readers

src/app/components/FacetSidebar/FacetSidebar.jsx
This is for #107 .
Tested with VoiceOver but FireFox doesn't seem to read them and I can't figure out the FF settings.
I'm following these keyboard navigation interactions from webaim: http://webaim.org/techniques/keyboard/
This PR also ties in with #108. It seems that the `spacebar` is the correct key to expand a dropdown instead of enter (enter would be to select an option). But, FF doesn't follow this rule. Neither `space` or `enter` expands a dropdown menu in FF. The tested this functionality on this page, also from webaim, http://webaim.org/techniques/forms/controls. The dropdown select menus don't open up in FF, but you can select with the up and down arrows. That's the same interaction in the facets dropdown.
I think it's a good start and set of rules to follow but user testing …
=> Adding tabIndex to fieldset so voice over reads the legend.

src/app/components/Results/Results.jsx
Also added `rel="prev"` and `rel="next"` to the previous and next links as per [recommendation](https://webmasters.googleblog.com/2011/09/pagination-with-relnext-and-relprev.html).
I'm just not sure if adding the `tabIndex` and `aria-label` attributes to the span to read the number of items displayed is the best approach.
=> Updating pagination links to be keyboard and voice over accessible.

.eslintrc, README.md, package.json, src/client/App.jsx, webpack.config.js
Adding react-a11y to check react component accessibility at run time and eslint-plugin-jsx-a11y to catch accessibility issues when running code through eslint.
=> Adding React specific a11y packages

src/app/components/FacetSidebar/FacetSidebar.jsx, src/app/components/HoldPage/HoldConfirmation.jsx, src/app/components/HoldPage/HoldPage.jsx, src/app/components/HoldRequest/HoldRequest.jsx, src/app/components/Home/Home.jsx, src/app/components/ItemPage/ItemPage.jsx, src/app/components/SearchResultsPage/SearchResultsPage.jsx, src/client/styles/components/FacetSidebar.scss, src/client/styles/main.scss, src/client/styles/toolkit/_css3.scss, src/client/styles/toolkit/_grid.scss, src/client/styles/toolkit/_media-queries.scss, src/client/styles/toolkit/_microformats-mixins.scss, src/client/styles/utils/variables.scss
Updating related pages to use the grid system.
Updated layout can be found on dev-discovery.nypl.org. This is a partial PR where I want feedback to see how the layout is building up, so only the large components on the page have been updated. All pages use the `content-wrapper` rules, the search results page the facets use 1/4 of the width and the results 3/4 of the width, and the item hold request and confirmation pages are broken down into three parts.
=> Adding grid system and other related toolkit scss.

src/client/styles/components/Account.scss, src/client/styles/components/Advanced.scss, src/client/styles/components/Breadcrumbs.scss, src/client/styles/components/FacetSidebar.scss, src/client/styles/components/Feedback.scss, src/client/styles/components/HoldPage.scss, src/client/styles/components/Home.scss, src/client/styles/components/Item.scss, src/client/styles/components/Results.scss, src/client/styles/components/Search.scss, src/client/styles/components/Tabs.scss, src/client/styles/main.scss, src/client/styles/toolkit/_colors.scss, src/client/styles/toolkit/_forms.scss, src/client/styles/toolkit/_grid.scss, src/client/styles/toolkit/_microformats-mixins.scss, src/client/styles/utils/base.scss, src/client/styles/utils/variables.scss
Colors and color variable names have been updated in design toolkit:
https://github.com/NYPL/design-toolkit/blob/master/sass/_colors.scss
Hyphenation is the variable name pattern now: e.g. `pagetextcolor` becomes `page-text-color`
Link, button, background, and border colors have been updated.  I [flagged](https://github.com/NYPL/design-toolkit/issues/22) the color contrast issues in the design toolkit.  Some of the styling looks weird (e.g. tables), but that should be fixed in subsequent PRs.
=> Update colors from updated toolkit colors #147

src/app/components/Hits/Hits.jsx, src/app/components/Results/ResultItems.jsx, src/app/components/Results/ResultsList.jsx, src/app/utils/item.js, src/client/styles/components/Results.scss, src/client/styles/components/Search.scss, test/unit/Hits.test.js, test/unit/ResultItems.test.js
Based on [design toolkit UI for search results](https://nypl.github.io/design-toolkit/discovery-search.html), I made an initial effort to implement those design recommendations.
This only should affect the right-hand-side of the search results page.  Mostly changes to CSS and HTML.  I made an effort to update the tests as well, but I may have missed some.
Known differences between this PR and the design specs (to be addressed another time):
- No "start over" button
- Sort component remains a select tag (the design had a hidden list component and button)
- Call number remains
- Original pagination styles remain
=> Results redesign #165

src/app/components/ItemPage/ItemPage.jsx, src/app/components/Results/ResultsList.jsx, src/app/utils/item.js, src/server/ApiRoutes/ApiRoutes.js
This should allow ~10M records to be shown
I also updated some field names that have changed since the previous API version.  It looks like most if not all items are missing "location" field currently, so temporarily assigning SASB to them.
#178
=> Update api endpoint

src/app/components/FacetSidebar/FacetSidebar.jsx
Getting the total count for each facet field and then adding the correct percentage to each individual facet item.
I noticed that when a number has more than 5 digits (also depending on the length of the facet name), it begins to float past the right border. I will open a ticket for this in design-toolkit.
=> Adding percentage class to individual facets.

src/app/components/FacetSidebar/FacetSidebar.jsx
#222 
This doesn't do much right now, but this method can grow to actually grab ten more facets. Right now it hides the button if it is unnecessary. This is kind of a dumb PR.
=> shows get ten more if there are more than ten to show

src/app/components/FacetSidebar/FacetSidebar.jsx
Fixes #259 
Using React's `ref` because sometimes clicking on the label or the svg arrows, did not make it actually click on the appropriate DOM element.
=> #259 referencing the button when clicking.

src/app/components/FacetSidebar/FacetSidebar.jsx
#246.
This also removes the date fields, in alignment with the removal of dates as facets in the Discovery API. (You can see they no longer appear in the deployed site or in beta-v1/master). We can discuss how we want to bring this back (as a filter and not as a facet?), but for now it is gone.
=> Reorder facets

src/app/components/FacetSidebar/Facet.jsx, src/app/components/FacetSidebar/FacetSidebar.jsx
This is a big one...
Each facet will now control its own state. This creates a bug where only one facet is selected at a time, but it's easier to debug now.
Also, the first facet clicked should show up now. We had the problem were the previous selection showed up instead of the current one.
This also addresses #237 - collapsing the facets on page load.
=> Facet sidebar refactor

src/app/components/FacetSidebar/Facet.jsx, src/client/styles/components/FacetSidebar.scss
Added functionality to display more facets when there are more than X number of them. The API is currently only returning at most 10 values, so I tested with a max display of 5 items.
So 5 facets will display and the button will tell you how many more are available to show. The 5 number was just for the picture, I reverted back to a minimum of 10 to display and the button will show how many more can be displayed.
=> Adding functionality to show more facets.

src/app/components/Breadcrumbs/Breadcrumbs.jsx, src/app/components/ItemPage/ItemPage.jsx
For #341.
Is this the right syntax for combo search and filtering? Working for me. This is the only place it is triggered -- when searching and filtering, then clicking down to the item page. The "Items" breadcrumb is where this is applied.
=> updates to use filters in breadcrumbs query

src/app/components/ItemPage/ItemPage.jsx
this is related to #340. There are a few other `a` tags that don't belong in the results list but they are related to holds, so not being used right now...
=> changes a to Link where applicable on ItemPage

README.md, package.json, src/app/components/HoldRequest/HoldRequest.jsx, src/app/stores/PatronStore.js, src/app/utils/item.js, src/server/ApiRoutes/itemSearch.js, test/unit/HoldRequest.test.js
For [#376](https://github.com/NYPL-discovery/discovery-front-end/issues/376) 
This PR is to refactor HoldRequest component. Generally, it adds checks and fallbacks for the props passed to it. Also, it adds an error page for no records found and an error instruction for invalid patron data. As updating these fallbacks, this PR makes minor updates to related functions in `src/utils`, too.
This PR also adds unit tests for HoldRequest.
=> 376 refactor hold request component

src/app/components/ItemPage/ItemHoldings.jsx
Fixes #398 .
Removes the link to request forms but keeps the request hold button for ReCAP items. I kept the code and just commented it out until everyone figures out what they want :confused:.
=> Removing the request link for nypl items.

src/app/components/Hits/Hits.jsx, test/unit/Alt.test.js, test/unit/Breadcrumbs.test.js, test/unit/Hits.test.js, test/unit/Home.test.js, test/unit/ResultItems.test.js, test/unit/SearchResultsPage.test.js
Updating tests to be somewhat stable. Ignore tests for the breadcrumbs. I added a ticket to update that component in the Hold pages (which are the tests that break).
Will need to add new ones eventually but at least this sort of gets us up and running from a better version than before.
Also, didn't bother to really fix tests where things will get updated.
=> Test update

src/app/components/HoldPage/HoldConfirmation.jsx, src/app/components/HoldRequest/HoldRequest.jsx, src/app/utils/item.js
Fixes #414 to include NYPL ReCAP items to the "request a hold" list.
Simple logic for now. Just checking to see that if there is a `holdingLocation`, that the word `offsite` is there.
We will be getting better checks later on.
=> Displaying the request hold button for NYPL ReCAP items.

src/server/ApiRoutes/Search.js
Fixes #256 
Examples: 
* http://dev-discovery.nypl.org/search?q=华 now gives the correct results (based on https://api.nypltech.org/api/v0.1/discovery/resources?q=华)
* http://dev-discovery.nypl.org/search?q=m%C3%A9xico%20y%20sus%20alrededores now returns correct results (based on https://api.nypltech.org/api/v0.1/discovery/resources?q=m%C3%A9xico%20y%20sus%20alrededores)
=> Encoding search keywords before adding to query for the API endpoint.

src/app/components/HoldPage/HoldConfirmation.jsx, src/app/components/HoldRequest/HoldRequest.jsx, src/app/components/Item/ItemHoldings.jsx, src/app/utils/item.js
WIP until we get the final say regarding delivery locations, but this is part of it, to have default/hardcoded delivery locations. I also reworked a lot of the data workflow and updated variables names to be more consistent.
A lot of it here. The `HoldRequest` component is now (actually, again) rendering the delivery locations as multiple options. It's not a list but we can worry about that later once we get the actual design.
I also hardcoded a specific nypl-owned recap item to test: b13340250 (http://dev-discovery.nypl.org/bib/b13340250 -> go to Hold Request page - it should have three delivery locations just to display).
All other non-nypl ReCAP items should have one delivery location going to SASB.
Non-ReCAP items just don't display the "Request" button at all.
=> Hardcode delivery location

src/app/components/Hits/ClearHits.jsx
Makes "Clear current search query, filters, and sorts" a link for no JS use. If
=> Made 'clear facet' a link for no js.

src/app/components/BibPage/BibPage.jsx, src/app/components/Item/ItemHoldings.jsx, src/app/components/Pagination/Pagination.jsx, src/client/App.jsx
Fixes #482 .
When the API is back up again, check out this bib: http://dev-discovery.nypl.org/bib/b12403270.
When you click on the next/prev buttons, the url will change to `/bib/b12403270?itemPage=2`, `/bib/b12403270?itemPage=3`, etc. It should work if you copy the url and open it up in a new browser. But, this won't (and shouldn't) work in a no-js scenarios. If there's no js, there's no pagination so the url query won't do anything.
=> Adding client-side query routing to bib page for items.

package.json, src/app/actions/Actions.js, src/app/components/ElectronicDelivery/ElectronicDelivery.jsx, src/app/components/ElectronicDelivery/ElectronicDeliveryForm.jsx, src/app/stores/Store.js, src/app/utils/formValidationUtils.js, src/server/ApiRoutes/Hold.js
Fixes #492 - adding server side validation to the form.
The validation function is used for both the server and client side so updating it for both should be easy once the updated requirements are fulfilled by management.
Example: http://dev-discovery.nypl.org/hold/request/b95618-i138987/edd
Turn JS off and try submitting. The url you will get back if there are errors looks url, but it's the easiest way to pass patron and error data from the server to the client to be rendered. Next step can be to make it better but for now it works and I think we should keep moving with that. Besides, not many will use it without js.
Please try to break it and let me know if there are any issues. Again, this is just a skeleton since it's not hooked up to an actual API yet, but just checking the form …
=> Edd form validate server

src/app/components/BibPage/BibMainInfo.jsx
Whoops -- did this on a branch named for something else -- but does as described. Links author to match the mockup.
=> adds logic to link specifically the author field

src/app/components/SearchPagination/SearchPagination.jsx, src/app/components/SearchResultsPage/SearchResultsPage.jsx, src/client/styles/components/SearchPagination.scss, src/client/styles/main.scss
This PR is to make the new pagination UI for search results page. The PR create a new class for the new pagination so we can still use the old one in another component.
The PR solves the issue of [#491](https://waffle.io/NYPL-discovery/discovery-general/cards/595e516d05733c02ea3e90b8)
The design can be seen here
https://drive.google.com/drive/folders/0B2LQIUUuUDJdR3ZZc3d6M0h1UWc
The PR mainly focus on the new functionality, so it does not fit the design 100% and also accessibility requirements. The styles are temporarily too. We will update it after we have the design for the toolkit.
@ricardoom
=> New pager for search results

package.json
This bumps up the toolkit and does what is needed to get package.json running temporarily... but haven't had time to do a comprehensive search through and make sure all of our API calls are running properly. At a glance, seems OK, but I will continue to investigate...
=> bumps toolkit and (temporarily) swaps alt for dgx-alt-center

src/app/components/BibPage/BibDetails.jsx, src/app/components/BibPage/BibMainInfo.jsx, src/app/components/BibPage/BibPage.jsx, src/app/components/BibPage/Definition.jsx, src/app/components/BibPage/MarcRecord.jsx, src/app/components/Item/ItemHoldings.jsx
Fixes #519 
There are still three `<span>`s inside the `dl` which I don't like but it's how React is rendering the components. We can iterate on that later on. Created a new component `Definition` which is just like `DefinitionList` except it returns the definition term/definition wrapped in a `span`.
=> Resolving the multiple definition lists in the bib page.

src/app/components/HoldConfirmation/HoldConfirmation.jsx
This PR adds a new start over button on the confirmation page based on the mockup.
https://app.moqups.com/digitalrepository@nypl.org/55BjtB7Pm0/view/page/a0f66a95b
can be tested on dev now.
=> Added start over button and related routes.

src/app/utils/item.js
Fixes #547 
Using the exact holding location data from the API. It was modified before when the item had "offsite" in it's prefLabel.
=> Displaying the holding location without any mapping for each item.

src/client/styles/components/Sorter.scss, src/client/styles/main.scss
Sort of fixes #467 
Sort of because the design-toolkit has this element as a `button`/`ul` combo but it should really be a `select` element for a11y.
CC @ricardoom
=> Sorting widget v2 or something

src/app/utils/item.js
Fixes #577 
Only displaying the "Request" button if `requestable` is true and there's `offsite` in the holding location string.
Examples:
* http://dev-discovery.nypl.org/research/collections/discovery-beta/search?q=toni%20morrison
* Appearing:
* http://dev-discovery.nypl.org/research/collections/discovery-beta/bib/b14417507
* Not Appearing (but was before):
* http://dev-discovery.nypl.org/research/collections/discovery-beta/bib/b15262926
* http://dev-discovery.nypl.org/research/collections/discovery-beta/bib/b16346821
=> Adding logic to update whether the Request button shows up or not.

src/app/components/BibPage/BibPage.jsx, src/app/components/SearchResultsPage/SearchResultsPage.jsx
Fixes #585 - for the most part. Other pages are being worked on and they should update the title to "Research Discovery (beta)" ( @ktp242 for the pages you're working on)
@wlla , do you think we still need the aria-label for the page h1 header on the Search Results page that says "Search results for Hamlet page 1 of 20" (for example)?
=> Updating name to Research Discovery (beta)

src/app/components/ElectronicDelivery/ElectronicDeliveryForm.jsx
I was trying to update the previous EDD form PR but it got merged. So now here is the new PR!
This PR updates the logic to show the error message for page number fields. Previously each fields had their own but identical error messages and they were shown with each field's own error input. But now, based on the content updates, these two page fields will only show one error message together as long as one field has a bad input.
This PR still keeps the method to validate page number fields separately, but the results will be merged by the logic in `ElectronicDeliveryForm.jsx`
The content mock-up,
https://app.moqups.com/digitalrepository@nypl.org/55BjtB7Pm0/view/page/a7cc00da8
=> Update edd form page error logic

src/app/components/ElectronicDelivery/ElectronicDelivery.jsx, src/client/styles/main.scss
This is for #597. I shouldn't have to add this extra shim, but the `<li>` tags do not honor what should be in the toolkit... would like to investigate but maybe will be resolved with a toolkit bump in the future. CC @ricardoom
=> styles raised error based on toolkit

src/app/components/HoldRequest/HoldRequest.jsx
This PR adds the check for no delivery room from the API.
Example: http://dev-discovery.nypl.org/research/collections/discovery-beta/hold/request/b17194537-i18803229
Fix #593
=> Added the check if there's no delivery room.

src/app/components/HoldRequest/HoldRequest.jsx
This PR adds the default delivery location to the Hold Request form. The logic will be
1) If the item has physical delivery locations, the default will be the first location.
2) If the item has only EDD, the default delivery location will be EDD.
on dev now
=> Add default delivery location

src/app/utils/formValidationUtils.js
This PR updates the validation for chapter title in EDD form. Now the chapter title can be a string such as `chapter 4` or `IX`. @RobKelley @seanredmond @gkallenberg 
It fixes the issue #615 and [DIS-92](https://jira.nypl.org/browse/DIS-92)
On dev now
=> Updated the validation for chapter title.

src/app/components/HoldRequest/HoldRequest.jsx
This PR adds the logic to skip rendering submit request button on Hold Request page if for some reason the patron doesn't get any delivery locations back from the API and also no EDD available. The content for the no delivery location is temporary and needs to be created.
=> Block submitting when no results

src/app/components/HoldConfirmation/HoldConfirmation.jsx, src/app/utils/formValidationUtils.js
Should fix #637 
I think the problem is we removed the validation for non-required fields so once the script in `src/app/utils/formValidationUtils.js` line 131 loop through the form, it can't find the respective key within the object `fieldsToCheck`.
=> Fallbacks for not necessary edd form fields

src/client/styles/components/_forms.v2.scss, src/client/styles/style-v2.scss
Fixes #648 
It's so odd that I couldn't put the styles together or else it wouldn't work. I tried:
```
&::placeholder,
&::-webkit-input-placeholder,
... etc
```
So, it seems like they have to be in separate rules to work. Got the pseudo classes/elements from this recent article:
https://css-tricks.com/almanac/selectors/p/placeholder/
=> Making the placeholder text darker for the omnisearch input field.

src/app/components/BibPage/BibPage.jsx, src/app/components/ElectronicDelivery/ElectronicDelivery.jsx, src/app/components/ElectronicDelivery/ElectronicDeliveryForm.jsx, src/app/components/HoldConfirmation/HoldConfirmation.jsx, src/app/components/HoldRequest/HoldRequest.jsx, src/app/components/Item/ItemHoldings.jsx, src/app/components/Item/ItemTable.jsx, src/app/components/Item/ItemTableRow.jsx, src/app/components/Results/ResultsList.jsx, src/app/components/SearchResultsPage/SearchResultsPage.jsx, src/client/styles/components/HoldConfirmation.scss, src/client/styles/main.scss, src/server/ApiRoutes/Bib.js, src/server/ApiRoutes/Hold.js
This PR creates the back to results link on confirmation page. When there's no `this.props.searchKeywords`, it won't render the link. One thing to notice and so I need your suggestions is that it is not going to work while no js, such as the link of `Search Results` in <Breadcrumbs>. The reason is that when no js, it is not a single page application anymore, so no `this.props.searchKeywords` will be passed from routes. We can pass the keywords with URL, but then we have to add one more variable to it. Any thoughts???
Btw, the styles are temporary, it should come from toolkit later.
=> Back to search button

src/app/components/ResultsCount/ResultsCount.jsx, src/app/components/SearchResultsPage/SearchResultsPage.jsx
Fixes #669. Try http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/search?filters[creatorLiteral]=Yi,%20Yong-p%CA%BBil.
=> Fixing issue where 'no results found' does not render.

src/app/components/HoldRequest/HoldRequest.jsx
Updates the logic for default delivery option. Now EDD will be the first option if it is available. If no EDD, the first delivery location will be the default. If no EDD or any delivery location, we will render an error message.
On dev now. Examples,
http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/hold/request/pb871379-pi3799305
http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/hold/request/pb2641482-pi4786093
=> Make default location option edd

src/app/components/Application/Application.jsx, src/app/components/BibPage/BibPage.jsx, src/app/components/ElectronicDelivery/ElectronicDelivery.jsx, src/app/components/HoldConfirmation/HoldConfirmation.jsx, src/app/components/HoldRequest/HoldRequest.jsx, src/app/components/Home/Home.jsx, src/app/components/SearchResultsPage/SearchResultsPage.jsx
This PR updates the titles and thus the titles on the browser tabs for each page. For now,
the homepage will show `Shared Collection Catalog | NYPL`, 
search result page will show `[keywords] | Search Results | Shared Collection Catalog | NYPL`,
bib page will show `[title] | Shared Collection Catalog | NYPL`,
hold request page will show `[title] | Shared Collection Catalog | NYPL`,
EDD page will show `[title] | Shared Collection Catalog | NYPL`,
confirmation page will show `[title] | Shared Collection Catalog | NYPL`.
The result can also be seen on the dev
Let me know if the contents need to be updated!!! @courtneymcgee
=> Added titles to every page.

src/app/utils/utils.js
This fixes the specific #667 issue of not getting results for `Yi, Yong-p'il` on http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/bib/b5283896 .
This also partly fixes #655 with getting links from the bib page working.
For comparison, here are the results from the API: https://api.nypltech.org/api/v0.1/discovery/resources?filters[creatorLiteral]=Yi,%20Yong-p%CA%BBil .
=> Encoding filter values before sending it to the API to get correct results.

src/app/components/BibPage/BibDetails.jsx, src/app/components/ResultsCount/ResultsCount.jsx, src/app/components/SearchResultsPage/SearchResultsPage.jsx
Fixes #668 .
Displays "x results for ....".
Examples:
1) Search Keyword `hamlet`: `2,320 results for search keyword hamlet.` http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/search?q=hamlet
2) Author: `3,209 results for Author Shakespeare, William, 1564-1616.` http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/search?filters[creatorLiteral]=Shakespeare,%20William,%201564-1616.
3) Title: `8,017,731 results for Title Cymbeline : complete and unabridged / the text conforming to the latest scholarly edition.`
4) Subject: `8 results for Subject Brel, Jacques.` http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/search?filters[subjectLiteral]=Brel,%20Jacques.
NOTE: Title seems to be a bit buggy but may be API …
=> Search results context

src/app/components/HoldConfirmation/HoldConfirmation.jsx
This PR fixes the missing phone number anchor on ask nypl info. updates on dev now.
=> Added the anchor back.

src/app/components/ResultsCount/ResultsCount.jsx, src/app/components/SearchResultsPage/SearchResultsPage.jsx
Fixes #683 
When selecting a value from the dropdown, the results will display the selected option.
`All fields` -> `x results for keyword ...`
`Title` -> `x results for title ...`
`Author/Contributor` -> `x results for author ...`
Currently on dev.
CC @courtneymcgee
=> Field context results

.ebextensions/02_cloudwatch_agent_config.config, .ebextensions/03_enable_log_streaming.config, .gitignore, logger.js, package.json, server.js
Fixes #708 .
Adding the `winston` npm package and set up eb config files and a logger instance file - all based on the work in the [discovery-api](https://github.com/NYPL-discovery/discovery-api). This PR just sets up the logging but there are still lots of `console.log` and `console.error` messages in the app. I wanted to get feedback on what has been done so far and if any AWS configs need to be updated.
I deployed it to dev and this is what the log has in cloudwatch in `/aws/elasticbeanstalk/discovery-ui-dev/var/log/nodejs/nodejs.log`:
I need to work with @ricardoom to remove a lot of the debug messages from the [design-toolkit](https://www.npmjs.com/package/@nypl/design-toolkit) npm package (but should be a different issue).
=> Winston logging

src/app/components/ElectronicDelivery/ElectronicDelivery.jsx, src/app/components/HoldConfirmation/HoldConfirmation.jsx, src/app/components/HoldRequest/HoldRequest.jsx, src/server/ApiRoutes/Hold.js
This PR handles the error after submitting a hold request to the API. It renders a general error message on the page, also offers the link to search results again or start all over.
=> Hold confirmation error

src/app/components/HoldConfirmation/HoldConfirmation.jsx
This PR fixes the header headings on Request Confirmation page and its error page. Related to issue #676 and #718 
After we bump up a version of tool-kit, then we can import  the design changes for it. Can be seen on dev now.
=> Updated headings.

src/app/components/Results/ResultsList.jsx, src/app/components/ResultsCount/ResultsCount.jsx, src/app/components/SearchResultsPage/SearchResultsPage.jsx
This PR fixes the issue #674. It updates the headings on search results page. Can be viewed on dev.
http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/search?q=peach
One thing I want to confirm is that the structure now of Bib details is
```
<div class="nypl-results-item-description">
<ul>
<liText</li>
<li>Moskva: 1965</li>
<li>1 item</li>
</ul>
</div>
```
Is this correct?
Or should I remove the `<div>` and apply ` class="nypl-results-item-description"` to the  `<ul>`
=> Fix header search results page

src/app/components/HoldConfirmation/HoldConfirmation.jsx
The delivery location logic needed to be above the html rendering logic. It was not displaying the location name before.
=> Moving delivery location logic above DOM rendering logic.

src/server/ApiRoutes/Search.js
Fixes #746 
Examples: 
* http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/search?q=a%20life%20for%20a%20life%3A%20a%20novel
* http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/search?q=aufstieg%20und%20niedergang%20der%20r%C3%B6mischen%20welt
=> Un-encoding the search string.

src/app/utils/item.js
Fixes #752 
No longer using "USE IN LIBRARY" to dictate if an item is a non-ReCAP NYPL item. Checking to see that the loc code does not start with "rc".
=> Updating the logic for non-recap nypl items.

src/app/components/ElectronicDelivery/ElectronicDelivery.jsx, src/app/components/HoldConfirmation/HoldConfirmation.jsx, src/app/components/HoldRequest/HoldRequest.jsx
Fixes #741 
This is up on DEV and QA. QA is the place to test since the catalog links go to the Hold Request page on QA. This is using the `fromUrl` that Kevin set up in Classic to link back to Classic.
How to test:
-- From Classic:
1) Start on https://nypl-sierra-test.iii.com/search~S98/?searchtype=X&searcharg=The+Victoria+history+of+the+county+of+Sussex&searchscope=98&sortdropdown=-&SORT=DZ&extended=0&SUBMIT=Search&searchlimits=&searchorigarg=XThe+Victoria+history+of+the+county+of+Sussex%26SORT%3DDZ
2) Click on the "Request from off-site storage".
3) Submit either an EDD or a Physical request.
4) You should get a confirmation page with two links to the catalog and a link to "try" Discovery.
5) 💰 
-- From Discovery:
Starting from a search query:
1) Start on …
=> Classic link

src/server/ApiRoutes/Bib.js
Fixes #773.
Example:
Instead of displaying an `internal server error` message like here:
https://qa-www.nypl.org/research/collections/shared-collection-catalog/bib/b7777777
redirect to the 404 page:
http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/bib/b7777777
=> Server redirect if fetching a bib fails on the server side.

src/app/components/BibPage/BibDetails.jsx, src/app/components/BibPage/BibPage.jsx, src/app/utils/item.js, src/app/utils/utils.js
Fixes #784 
NOTE: This PR is the logic/data part. @ricardoom , let me know where it should be located, how it should look, or any other changes. I think you mentioned to make the link open in new pages so I did that.
This PR is:
1) Extracting each item's `electronicLocator` array.
2) If there are multiple items with multiple `electronicLocator` array, it will aggregate them all into one single array.
3) It will render that list of links (or a single link) in the Bib page.
Examples:
* http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/bib/b12170263
* http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/bib/b17997741
* http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/bib/b14924644
* …
=> Electronic locator display

src/app/components/BibPage/BibPage.jsx
Fixes #774 ([DIS-127](https://jira.nypl.org/browse/DIS-127))
These two bibs (b12155601, b12251256) have the `partOf` data in the production API but not the development API, so here are screenshots:
=> Adding a bib's 773 field to the bib record page.

package.json, src/app/components/Feedback/Feedback.jsx
Fixes #802
Keeps focus inside the widget when it's open. Also updated it so that it clicking outside of the form closes it, which is part of the focus-trap-react package.
=> Adding focus trap to the feedback component.

src/app/components/BibPage/BibDetails.jsx
Fixes #811 
Just switching `prefLabel` for `label` for electronic resource items.
=> Using 'label' instead of 'preflabel' for electronic resource items.

src/server/ApiRoutes/Bib.js, src/server/ApiRoutes/Hold.js, src/server/routes/api/index.js
Fixes #813 
I'm adding more information to the error messages in the log, but the app itself should not fail (or return a "internal server error") for these errors. The app should still run and the error messages will propagate to the app if applicable. I did add a better logic check for delivery locations retrieval. It seemed that one call failed because it didn't have delivery locations and it assumed there were. The endpoint for that error is also added.
=> Adding more and better error messages to api calling functions.

src/app/components/NotFound404/NotFound404.jsx
Fixes #822 
Forgot a `/` 😓 
Check it out on dev: http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/404
@gkallenberg
=> Added missing / to get to the homepage from the 404 page.

src/app/components/FilterPopup/FilterPopup.jsx, src/app/components/Filters/FieldsetDate.jsx, src/app/components/Filters/FieldsetList.jsx, src/app/components/SearchResultsPage/SearchResultsPage.jsx, src/client/styles/components/FilterPopup.scss, src/server/ApiRoutes/Search.js, test/unit/FieldsetList.test.js, test/unit/FilterPopup.test.js
Fixes #833 
* Settles the two async calls to the results and aggregations API endpoints.
* Adds the filters to the Store in the app when making new searches.
* Populates the filter popup with the updated format (materialType) and language filters along with the count.
* This fixes half of https://jira.nypl.org/browse/DIS-156 but breaking it up because it'll get too large adding the data back AND making it all work. That being said, applying the filters doesn't work for this PR, just displaying the results from the API again.
Up on dev.
=> Filter data in app

src/app/components/FilterPopup/FilterPopup.jsx, src/app/components/Filters/FieldsetList.jsx, src/app/components/Filters/SelectedFilters.jsx, src/app/components/ResultsCount/ResultsCount.jsx, src/app/components/SearchResultsPage/SearchResultsPage.jsx, src/app/utils/utils.js, src/client/styles/components/SelectedFilters.scss, src/client/styles/main.scss, test/unit/SelectedFilters.test.js
Fixes #841 - Rendering filter buttons and removing filters when clicked.
Jira ticket [DIS-161](https://jira.nypl.org/browse/DIS-161)
Example: 
1. Go to http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/search?q=war&filters[materialType]=resourcetypes%3Acar&filters[language]=lang%3Ajpn&filters[language]=lang%3Apol
2. Click on the `FILTER RESULTS` button.
3. Check out the selected filters:
4. Close the popup.
5. Click on a filter to remove it.
6. Open up the popup again and the filter should be removed.
**NOTE: This PR also fixes a few bug issues when filtering from the existing PR of #837 **
=> Remove filters

src/app/components/FilterPopup/FilterPopup.jsx, src/app/components/Filters/SelectedFilters.jsx, src/app/components/ResultsCount/ResultsCount.jsx, src/app/components/SearchResultsPage/SearchResultsPage.jsx, src/app/stores/Store.js, src/app/utils/utils.js, src/server/ApiRoutes/Search.js, test/unit/ResultsCount.test.js, test/unit/SelectedFilters.test.js
Fixes #844 and #846
1) Displays a warning specific to just using a search keyword:
* Search for `bike banana beans`
2) Displays a warning with a search keyword AND selected filters: 
* Search for `hamlet` and then select `Cartographic` and `Portuguese`.
=> Updating message for when there are no results with filters and without filters.

package.json, src/app/components/Application/Application.jsx, src/app/stores/PatronStore.js, src/server/routes/api/index.js
Hey, so this is a WIP. The Header component doesn't have a new npm version yet but this is what would be needed to simply pass the props to the `<Header>` component so it can render the patron's info on the server-side.
Each React app itself would need to have the `jwt` related npm packages and code to fetch a Patron's information so it can be handled correctly in the header. Otherwise, the header will simply fetch the Patron's data itself like always.
=> Test header server login

CHANGELOG.md, package.json, src/app/components/BibPage/BibPage.jsx
This PR is the hot fix to remove MARC on bib detail page as the link to webpack is not working now.
=> Added comments and version updates.

src/app/components/Filters/SelectedFilters.jsx, src/client/styles/components/SelectedFilters.scss, test/unit/SelectedFilters.test.js
Fixes #868
Adds a "clear filters" button in the same list as the selected filters. Clicking on it will remove all the filters and make a new search with the existing search keyword(s). Should work with and without JS.
=> Adding the clear all filters button/link on the search results page.

src/app/components/FilterPopup/FilterPopup.jsx, src/client/styles/components/FilterPopup.scss
Fixes #878
Fixes the close button not displaying correctly on mobile and minor styling to the popup when js is turned off.
Hard to replicate what's on the design-toolkit because of the difference in DOM structure.
=> Adding SCSS rules to better style the filter popup with no js.

CHANGELOG.md, package.json, src/app/components/HoldRequest/HoldRequest.jsx
Fixes #887 
Updated notification copy in support of January changes to hours.
Up on http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/hold/request/b10980129-i12024369
CC: @natalietsch @katesweeney
=> Updated HoldRequest component for January 2018 changes to hours of operation

src/app/components/SearchResultsPage/SearchResultsPage.jsx, src/app/components/Sorter/Sorter.jsx, test/unit/SearchResultsPage.test.js
moves these components below the search results page header to it's own <div> wrapper above the ResultsList component
=> Move ResultsCount and Sorter down

.eslintrc, src/app/components/BibPage/BibPage.jsx, src/app/components/BibPage/MarcRecord.jsx, src/app/components/Breadcrumbs/Breadcrumbs.jsx, src/app/components/FilterPopup/FilterPopup.jsx, src/app/components/Filters/FieldsetDate.jsx, src/app/components/Filters/FieldsetList.jsx, src/app/components/Filters/SelectedFilters.jsx, src/app/components/Pagination/Pagination.jsx, src/app/components/SearchResultsPage/SearchResultsPage.jsx, src/app/utils/utils.js, src/client/styles/components/BibPage.scss, src/client/styles/components/FilterPopup.scss, src/client/styles/components/SelectedFilters.scss, src/client/styles/main.scss, src/client/styles/utils/mixins.scss, src/server/ApiRoutes/Search.js, test/unit/FilterPopup.test.js, test/unit/Pagination.test.js, test/unit/SelectedFilters.test.js
Lots of changes for the UI look of what was once the filter popup into the filter dropdown.
The name of the component and class names have not changed and still include "modal" in there, even though that's not correct and should eventually be updated. This is half of a rewrite to get the UI looking somewhat correct and will have to refactor this later on with @ricardoom 's help and updates to the Design Toolkit.
This is currently up on dev-discovery. Example filtered result: http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/search?q=hamlet&filters[materialType][0]=resourcetypes%3Atxt&filters[dateAfter]=1000&filters[dateBefore]=2000
=> Dropdownfilters

src/client/styles/components/Sorter.scss
Fixes #895 - moving the sorter dropdown to the right side of the page. A few overrides to the Design Toolkit but we'll get there in the next iteration/refactor.
Up on dev-discovery.nypl.org
=> Adding scss to override DT to put the sorter on the right side.

src/app/components/BibPage/BibDetails.jsx
In order to better distinguish between clicks on electronic resources,
add external URL to the event data.
Since this kind of takes the "D" out of "DRY" one could argue that creation of the creation of the label (or really of the whole `<a>` element should be broken out into a function.
=> Add URL to electronic resource events

src/app/components/Buttons/SearchButton.jsx, src/app/components/Buttons/SearchIconReversed.jsx, src/app/components/Search/Search.jsx, src/client/styles/components/FilterPopup.scss, src/client/styles/components/Search.scss, test/unit/Search.test.js, test/unit/SearchButton.test.js
Adds custom overrides for the omnisearch elements to stack the form elements when the viewport is reduced to its smallest size. Includes a stab at adjusting the form elements to inline when viewport is larger.
CSS and HTML structural changes are included as well as an addition to the new filter scss to give the "Results.." text a push down below the submit button for mobile view.
=> Mobile stacked form view attempted fix

src/app/components/ResultsCount/ResultsCount.jsx, src/app/components/Search/Search.jsx, src/app/components/SearchResultsPage/SearchResultsPage.jsx
Fixes #911  - leave filters alone when the keyword is updated.
This is up on dev right now.
**Note**: What should also be tested is whether a user changes the keyword search, has the dropdown open, clicks on `Apply filters`, and expects the keyword to also be updated (since this is now a different button...) 
@katesweeney  @ricardoom @wlla  - let me know what you think on the above note.
=> Allowing filters to persist when the keyword is updated.

src/app/components/BibPage/BibPage.jsx, src/app/components/ElectronicDelivery/ElectronicDelivery.jsx, src/app/components/ElectronicDelivery/ElectronicDeliveryForm.jsx, src/app/components/FilterPopup/FilterPopup.jsx, src/app/components/HoldConfirmation/HoldConfirmation.jsx, src/app/components/HoldRequest/HoldRequest.jsx, src/app/components/Home/Home.jsx, src/app/components/LoadingLayer/LoadingLayer.jsx, src/app/components/SearchResultsPage/SearchResultsPage.jsx, test/unit/HoldConfirmation.test.js, test/unit/HoldRequest.test.js, test/unit/SearchResultsPage.test.js
This helps fix #938 by focusing on every `h1` on a new page when transitioning. When running a new search, the "Refine Search" title will be focused after the loading screen.
This is currently up on dev.
=> Focus check

src/app/components/BibPage/BibDetails.jsx, src/app/components/BibPage/BibPage.jsx
Changed the processing of the `note` field to a method and looping structure in BibDetails.jsx. The getNote() method initializes the note data and checks for missing or empty data and returns null. Otherwise, the note array is returned as is for output processing.
The output is set to display as a single note `<span>`, a list of stings, or, for the new structure, a list of `<h4>` and `<p>` elements. The `<h4>` contains the `noteType` string and the `<p>` tag displays the `prefLabel` string for each item in the array of objects.
See: https://jira.nypl.org/browse/SCC-320
=> Note structure changes

package.json, src/server/ApiRoutes/Search.js, webpack.config.js
Fixes bug where socket hangs up due to not encoding certain aggregations
queries.
Also adds FriendlyErrorsWebpackPlugin for more verbose webpack failures.
https://jira.nypl.org/browse/SCC-529
=> Fix aggregations url encoding bug

.env-sample, .gitignore, EBSVARS.md, README.md, appConfig.js, package.json, server.js, src/server/routes/nyplApiClient/index.js
This changes the official config variables supported for app config:
- Change case of clientId, clientSecret
- Deprecates APP_ENV to just set PLATFORM_API_BASE_URL directly
- Adds `.env-sample` and instructs use of `.env` as means to load
config values
- Adds simplified documentation for running with common configurations
Discussion invited. I'm trying to sand off some pain points for new users:
1. I've found `APP_ENV` a little confusing and since it only seems to control what platform api base URL you use, I propose we just allow one to set that directly. 
2. Also introduces use of `.env` as means to pass in env vars, which I've found much easier to use than passing them in on cmd line. Also is an opportunity to document vars in `.env-sample`
=> Change app config vars, documentation

webpack.config.js
Moves the inclusion of friendly-errors webpack plugin to only as needed
when NODE_ENV is development. Previously was included when building dist
for production, when it will not exist.
=> Fix fiendly-errors dev dependency include

src/app/components/BibPage/BibPage.jsx
Previously BibPage had a componentDidMount method to focus on an html element with id bib-title. This no longer exists. As a result, componentDidMount in Application.jsx (which depends on componentDidMount in all its children, including BibPage), was erroring, and not telling Application to listen to the Store as it was supposed to. Removing componentDidMount from BibPage now removes this error. As a result, delivery locations are fetched from the Store.
=> Remove componentDidMount from BibPage

src/app/components/Item/ItemHoldings.jsx, src/app/components/Results/ResultsList.jsx
This branch just changes a the action and label of a couple of ga events. First, it changes the action from "Bib Item Request", which was viewed as confusing, to simply "Item Request". Second, it changes the label by dropping the item id. This is to allow easier comparison of the number of events triggered from the search results page vs. the item details page. It was decided that the loss of information was acceptable because currently no one is looking at the richer information anyway.
=> Fix ga event action and label for item requests

CHANGELOG.md, README.md, package-lock.json, package.json, src/app/components/BibPage/BibDetails.jsx, src/app/components/BibPage/DefinitionList.jsx, test/unit/BibDetails.test.js
This PR basically adds two condition checks to see if the bib detail field is subject headings. If so, it will calls the addiontal string methods to generate new texts and URLs for the link.
Can be tested here locally,
http://local.nypl.org:3001/research/collections/shared-collection-catalog/bib/b21160519
Now the subject headings should look like
```
Amateur journalism > Australia > Periodicals
Amateur journalism
Australian Amateur Journalists' Association > Periodicals
Golden Hours Corresponding Club > Periodicals
```
And the filter values should be (as the example of the first subject heading)
```
Amateur journalism. > Amateur journalism -- Australia. > Amateur journalism -- Australia -- Periodicals.
```
=> Construct subject headings

src/app/components/Filters/FieldsetList.jsx, src/app/components/SearchResultsPage/SearchResultsPage.jsx, src/app/utils/subjectFilterUtils.js, test/unit/BibDetails.test.js, test/unit/subjectFilterUtil.test.js
This branch is meant to address the issue of partial subject literals not appearing as possible filters when a user 1) clicks on a subject on a bib page 2) clicks Refine Search  on the search results page.
This branch makes two changes:
1) It adds a method to explode the subject literals in the aggregations so that they will include a match to the partial subject literal
2) It makes the narrowSubjectFilters method return a new object rather than mutating the existing apiFilters object. This is to ensure that we do not lose filters when this method is called on the initial load.
Some issues with this PR:
1) Ideally we would use the same methods to split the subjectLiteral here as in the BibDetails component, but this seemed difficult to do
2) JSON.parse(JSON.stringify(--)) seems like a …
=> Add exploding of subject literals in aggregations

src/server/ApiRoutes/Search.js
This PR changes the way we populate subject literal filters in server side rendering so that it is not dependent on aggregations. The goal is to ensure that these filters will show up when directly navigating to search result urls
=> Add setting of subject literal filters in searchServer

src/app/components/SearchResultsPage/SearchResultsPage.jsx, src/app/utils/utils.js
Changes the way we find subject literal fields in the url from `===` to `includes`, so that we can recognize arrays of subject literals. This is because keyword search with an active subject literal treats the subject literal as an array with a single element. In particular, if you use browser navigation while doing keyword searches with an active subject literal, the subject literal will only sometimes appear in the filters as it currently is.
=> Populate subject literal on direct link

README.md, locationCodes.js
This change principally adds two new SASB scholar rooms: 217 and 223 to `./locationCodes.js`, enabling them to be labeled properly when they are presented as available delivery options for a given hold request.
This PR also includes an update to the README documenting generally how to add locations to this app.
=> Add mal17 mal23

src/app/components/SubjectHeading/SubjectHeading.jsx, src/client/styles/components/SubjectHeadings.scss
Changes the styling to set width attributes rather than position attributes. This seems to work better with very long titles. I also hope it will 1) be less brittle and 2) produce less unexpected behavior.
Note there are still some issues with very long titles, see e.g. http://localhost:3001/research/collections/shared-collection-catalog/subject_headings?fromLabel=%22Orchestrated+by+Ernest+Gold%2C+April+25%2C+1959.%22--The+life+and+music+of+George+Antheil%2C+1900-1959+%2F+by+Linda+Whitesitt.+Ann+Arbor%2C+Michigan+%3A+UPI+Research+Press%2C+c1983+%28Item+104%29&fromComparator=after and navigate to "Plast" orhaniza︠t︡si︠i︡a ukraïnsʹkoï molodi -- History -- Sources -- Bibliography -- Catalogs
=> Replace positioned with width

src/app/components/SubjectHeading/AdditionalSubjectHeadingsButton.jsx, src/client/styles/components/SubjectHeadings.scss
tweaks upon tweaks. Particularly- open top level headings have the slightly darker grey extend to the right edge as depicted in Figma. Also made the selector slightly more specific for the `border-bottom` styling.
=> Top level open heading grey extends to right edge

src/app/components/SubjectHeading/SubjectHeadingShow.jsx
Fixes a bug visible for example on the show page for 'African Americans -- Suffrage', in which the wrong heading is selected to show. This happens because the SubjectHeadings assume they should pre-open if they have children. The fix is to remove children we don't want to display when we process the context headings.
=> Add logic to remove superfluous children in context box

src/app/components/SubjectHeading/SubjectHeading.jsx, src/app/components/SubjectHeading/SubjectHeadingsList.jsx, src/client/styles/components/SubjectHeadings.scss
Adds some extra logic and styling to make sure that the main subject heading (either linked or on the show page) is highlighted and italicized, even if it has no children.
=> Highlight main no children

src/app/components/HoldConfirmation/HoldConfirmation.jsx
This adds custom messaging for case where patron attempts to place a hold but is blocked due to having a ptype that bars holds. Without this update, the text would just read "There is a problem with your library account.". With this update, in the case of a barred ptype, the patron sees "Your card does not permit placing holds on ReCAP materials."
This also fixes a minor bug where the controller was attempting to make a google analytics call on the server side (i.e. where `window` is `undefined`), leading to a ["Internal Server Error"](https://qa-www.nypl.org/research/collections/shared-collection-catalog/hold/confirmation/pb7388405-pi6575276?errorStatus=eligibility&errorMessage={%22eligibility%22:false,%22expired%22:false,%22blocked%22:false,%22moneyOwed%22:false,%22ptypeDisallowsHolds%22 …
=> Add messaging for ptype ineligibility

.travis.yml, package-lock.json, package.json
The babel config in 'package.json' was supposed to be implementing the 'istanbul' package for test coverage. But istanbul was misspelled anyway so it was never serving any purpose anyway...
=> Remove redundant babel config from 'package.json'

src/app/components/SubjectHeading/BibsList.jsx
Fixes a bug in `BibsList` method `updateBibPage`
1. `lastBib` and `firstBib` are determined programmatically from `bibPage` rather than being tracked in state
2. Use `Math.min` and `Math.max` to ensure we stay within bounds.
3. updating `bibPage` is done by setting it to the passed `page` parameter, rather than incrementing it.
=> Fix bug in BibsList pagination

src/server/ApiRoutes/SubjectHeadings.js
Not a breaking typo. But there was an extra "/" in all shep API calls
=> remove extra "/" from shep request url

package-lock.json, package.json
Update `@nypl/design-toolkit` to newest version, created due to conflicts with Node v10.
@danamansana
=> Bump @nypl/design-toolkit to v0.1.37

src/app/components/BibPage/BibDetails.jsx, src/app/components/BibPage/BibPage.jsx, src/app/components/BibPage/DefinitionList.jsx, src/app/components/SubjectHeading/SubjectHeading.jsx, src/server/ApiRoutes/Bib.js
This takes the SHEP API call out of the initial API call to Discovery for the bib data out of the `Promise.all`. It places it inside of a conditional in the `.then` to only make the call if the `subjectLiteral` property on the fetched bib has length. If it does and the call to SHEP API is successful, the response is stored in a `subjectHeadingData` property on the bib. In the component, if there is the `subjectHeadingData` property, it renders the subject headings with links to the SHEP show page. If that property does not exist, it falls back to the links to SearchResults with the `subjectLiteral` filter. There could be some tweaks to this logic. If that initial SHEP api call falls, there will is no re-attempt to integrating SHEP API.
=> SCC-1763 error handling for bib page

package-lock.json, package.json, src/app/components/SubjectHeading/NestedTableColumnHeading.jsx, src/app/components/SubjectHeading/SubjectHeading.jsx, src/client/styles/components/SubjectHeadings.scss, src/client/styles/components/SubjectHeadings/AdditionalSubjectHeadingsButton.scss, src/client/styles/components/SubjectHeadings/NestedTableColumnHeading.scss, src/client/styles/components/SubjectHeadings/SubjectHeading.scss, src/client/styles/components/SubjectHeadings/SubjectHeadingsTable.scss, src/client/styles/components/SubjectHeadings/SubjectHeadingsTableHeader.scss, src/client/styles/main.scss, webpack.config.js
Implements glob import for SCSS to make it easier to architect our SCSS in a componentized way.
This is a small task to allow for more seamless larger refactoring and restyling.
https://jira.nypl.org/browse/SCC-1839
No tests yet.
**Dependencies for merging? Releasing to production?**
Run `npm i` before running locally.
There is a pre-existing issue from changing the CSS wrapper class to the one from Header with the focus styling. I applied a band-aid to a couple elements I noticed in a previous PR. A nicer fix will be to come. Just wanted to note that here because it threw me off initially and to emphasize that it is unrelated to changes in …
=> SCC-1839 use glob import for component style sheets

src/app/components/SubjectHeading/SubjectHeading.jsx, src/app/components/SubjectHeading/SubjectHeadingsTableHeader.jsx
This PR swaps the positions of the `Title Count` and `Subheading Count` columns. It is an easy initial change for the new design.
https://jira.nypl.org/browse/SCC-1844 - task
https://jira.nypl.org/browse/SCC-1843 - story
=> SCC-1844 swap title count and subheading count columns

package-lock.json, package.json
`development` does not work locally with this automated upgrade of `webpack-dev-server` from '2.7.1' to '3.1.11'
=> revert bad dependabot upgrade

src/app/components/Breadcrumbs/Breadcrumbs.jsx, src/app/components/Results/ResultsList.jsx, src/app/components/SubjectHeading/SubjectHeadingsTableBody.jsx
I updated the Breadcrumbs component so that "Search Results" is only shown if there is indeed a search query.
I also updated the ResultsList component used on the SHEP show page, because it was adding "searchKeyword=undefined" onto the urls to bib show pages. Now, if there is a searchKeyword from the Store or from props, the query will be appended to the url. If not, it will just be the standard bib page url.
This exact logic could be tweaked. But it will stop most of the bad links to Search Results that we were finding.
https://jira.nypl.org/browse/SCC-1877
=> SCC-1877 / fix search results breadcrumb bug

src/app/components/SubjectHeading/NestedTableHeader.jsx, src/app/components/SubjectHeading/SortButton.jsx, src/app/components/SubjectHeading/SubjectHeadingsTableBody.jsx
I did this a little quick and dirty, but I believe I switched to this approach pretty cleanly. The inspiration for this came from wanting to disable the `SortButton` element if there is only one narrower heading. To accomplish this, the `NestedTableHeader` needed access to the number of narrower headings being rendered. Also, this approach makes it more obvious where and when the `NestedTableHeader` will be rendered.
=> SCC-1887 Proposed nested table change and disable sort columns when there is no sort functionality

src/app/components/BibPage/BibDetails.jsx, src/app/components/BibPage/BibPage.jsx, src/app/components/SubjectHeading/AdditionalSubjectHeadingsButton.jsx, src/app/components/SubjectHeading/NestedTableHeader.jsx, src/app/components/SubjectHeading/SortButton.jsx, src/app/components/SubjectHeading/SubjectHeading.jsx, src/app/components/SubjectHeading/SubjectHeadingsTableBody.jsx
(Formerly "Disable SortButton on main table header when not interactive")
The main change in this PR is to maintain the number of displayed narrower headings when resorting a nested table.
This PR also disables the SortButton on the main table header when not interactive. We could do this for the NestedTableHeader when there is only one subject heading, if that component had the number of narrower headings passed to it. That is what PR #1205 Proposed nested table change acccomplishes.
(Side note: ignore the branch name)
=> SCC-1865 maintain number of displayed subheadings when resorting nested table

src/app/components/SubjectHeading/SortButton.jsx
Small bug fix for `SCC-1865-debug`. SortButton created bugs if only one subject heading was displayed. We also could hide the '^', but when you click 'See more' , the '^' becomes relevant.
=> SCC-1865 debug SortButton interactivity

src/app/components/Item/ItemTable.jsx
This PR adds a check to make sure at least one item is not an e-resource before rendering the ItemTable, because this allows for empty tables on the SearchResults page.
=> Add check for e-resource before rendering item table

src/app/components/SubjectHeading/AlphabeticalPagination.jsx, src/client/styles/components/SubjectHeadings/AlphabeticalPagination.scss
I used working on SCC-1838 on the backend to simultaneously fix the UX for this feature by implementing the approach @hokei recommended 👍
Looks a little different than the current version, but will be a lot easier to maintain.
Problem with previous version (goes off page unpredictably):
Current version:
=> Add punctuation button and change approach to border styling

src/client/styles/components/ShepContainer.scss, src/client/styles/components/SubjectHeadings.scss
Quickest change for [SCC-1914] Show page info box jagged breakpoint. This change increases the screen width at which the left margin disappears. Right now, it is applied to both the show and index page, due to the HTML structure and current classname usage. We could also add another classname to `.nypl-column-full`<div> in the ShepContainer to only apply this change to the show page and not the index page.
=> SCC-1914 Fix breakpoint behavior for show page

src/app/utils/utils.js, test/unit/utils.test.js
This changes the behavior of the `basicQuery` util function to not return the default string of "q=" if there are no search parameters. Maybe this is over kill or more QA trouble than it is worth? I am trying to figure out how to eliminate the behavior we do not want more concisely, because I keep finding it.
**Why are we doing this? (w/ JIRA link if applicable)** 
There are JIRA tickets related to this. We do not want to pretend there are search results or show it in the breadcrumbs if a search was not actually made and if the data is not in the store or props for whatever reason.
**How should this be tested? / Do these changes have associated tests?** 
This effects two tests. I marked them as pending and left a temporary comment. I think @EdwinGuzman said the …
=> change the behavior of `basicQuery()` to avoid fake "Search Results"

src/app/components/SubjectHeading/AdditionalSubjectHeadingsButton.jsx, src/app/components/SubjectHeading/NestedTableHeader.jsx, src/app/components/SubjectHeading/SubjectHeading.jsx, src/app/components/SubjectHeading/SubjectHeadingsTable.jsx, src/app/components/SubjectHeading/SubjectHeadingsTableBody.jsx, src/app/components/SubjectHeading/SubjectHeadingsTableHeader.jsx
Implement React context (_legacy API_) for `container` rather than passing as prop. Also, there is a lot of stale code I believe. One thing I am not sure about is the `interactive` state/prop for the `AdditionalSubjectHeadingButton`. I believe we are not really using it any more?
Well, I managed to clean up some code! Also, we might be able to use context for other properties going forward and can follow this pattern.
Check the index and couple show pages. They seem to be working the same to me.
**Dependencies for merging? Releasing to production?**
None.
**Has the application documentation been updated for these changes?**
Not necessary …
=> SCC-1930/implement context for `container`

CHANGELOG.md, README.md, package-lock.json, package.json
[Related Jira ticket](https://jira.nypl.org/browse/RENO-1153)
**This PR does the following:**
- Updates dgx-react-footer to v0.5.4
- The footer update removes the Kievit font, Tumbler icon, and adds [system-font-css](https://github.com/jonathantneal/system-font-css) according to this [migration guide](https://docs.google.com/document/d/1gErDfbmTuKvSUkmfFnhRh9BAF1CCqUl66koTAtOZmdU/edit#)
=> RENO-1153-update-dgx-react-footer-to-0.5.4

src/app/components/SubjectHeading/NestedTableHeader.jsx, src/app/components/SubjectHeading/SortButton.jsx, src/client/assets/Ascending.jsx, src/client/assets/Default.jsx, src/client/assets/Descending.jsx
Implements the SVG assets for the sort buttons to match Ellen's design.
https://jira.nypl.org/browse/SCC-1961
**Questions for reviewer.**
Any thoughts on where the arrow icon components should go in the code base? Also, any ideas for fixing the bug described below? How is the spacing looking?
I did. There is currently a bug with the `calculateDirection` function. It returns the opposite direction for the initial sort, because it is intending to switch the current sort type. This manifests in the arrow appearing in the wrong direction for the default "alphabetical" sort.
=> SCC-1961/implement new sort button SVG

src/app/components/SubjectHeading/SubjectHeadingShow.jsx, src/app/components/SubjectHeading/SubjectHeadingsIndex.jsx, src/app/components/SubjectHeading/SubjectHeadingsTableBody.jsx
This PR changes the way the linked index view data is retrieved. One API call is made for the index with a 'linked' param, which is the subject heading UUID.
The context for the linked view comes after the top level index. It is harder to change the loading sequencing on the frontend for the two API queries this way.
https://jira.nypl.org/browse/SCC-1936
**Dependencies for merging? Releasing to production?**
There is a corresponding PR on the backend: https://github.com/NYPL/subject-headings-explorer-poc/pull/152
I did. There are some frontend tweaks that need to be made to properly condense the context part. I believe this just has to do with the "Range" …
=> Scc-1936/ make one API call for linked index

src/app/components/ShepContainer/ShepContainer.jsx, src/app/components/SubjectHeading/SubjectHeading.jsx
Removes the empty toggle button for subject headings with no narrower headings.
https://jira.nypl.org/browse/SCC-2011
=> SCC-2011/ remove dummy toggle button

package-lock.json, package.json
Styling from previous version of "@nypl/design-toolkit" was misapplying focus styling to all `<a>` tags.
https://jira.nypl.org/browse/SCC-2015
I did.
=> For production: bump @nypl/design-toolkit to "0.1.38"

src/app/components/ShepContainer/ShepContainer.jsx, src/app/components/SubjectHeading/Search/SubjectHeadingSearch.jsx
Zach said the first UI component is preferable to the breadcrumb. For the shep pages that is the autosuggest search box.
Check subject heading index and show page. Either append "#mainContent" to end of URL or tab to "Skip to main content"
PR author did
=> Change position of "mainContent" id on SHEP pages

src/app/components/Application/Application.jsx, src/app/components/BibPage/BibDetails.jsx, src/app/components/DataLoader/DataLoader.jsx, src/app/components/ResultsList/ResultsList.jsx, test/unit/DataLoader.test.js
This supersedes the previous PR for this issue to provide a less intrusive fix so there is less chance of introducing new bugs
This PR removes the `searchKeyworld` param from the bib url. It is in the href for bibs on the ResultsList for no-JS, but ends up not being there with JS. Originally, there was a click handler that updated the bib in the store and pushed the bib page URL without that param to the router. When the click handler was removed, the url with the `searchKeyword` end up becoming the one we routed to with or without JS. I also made the logic for whether or not to update the Store when using navigation buttons a little more strict.
This PR includes some other changes, like using router context in `DataLoader`, instead of passing location as a prop.
**Why …
=> Navigation bugs between search result pages and bib pages

src/app/components/SubjectHeading/BibsList.jsx, src/app/components/SubjectHeading/NeighboringHeadingsBox.jsx, src/app/components/SubjectHeading/SubjectHeadingShow.jsx
Remove tab index/focus for content boxes on show page, as suggested by Ellen and approved by Matt.
https://jira.nypl.org/browse/SCC-2023
PR author did.
=> SCC-2023/ Remove tab index for content boxes on show page
