- src/app/actions/Actions.js
- src/app/components/Breadcrumbs/Breadcrumbs.jsx
- src/app/components/FacetSidebar/DateRange.jsx
- src/app/components/FacetSidebar/FacetSidebar.jsx
- src/app/components/Hits/Hits.jsx
- src/app/components/Results/ResultsList.jsx
- src/app/components/Search/Search.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/app/routes/routes.jsx
- src/app/stores/Store.js
- src/server/ApiRoutes/ApiRoutes.js
The functionality is not in place to remove a selected filter but the selected filter now appears on top. It's not styled at the moment as well.
The URL query is also updated so the linked facets can work.
> Discovery facets

- src/app/components/ItemPage/ItemPage.jsx
- src/app/components/Results/ResultsList.jsx
Small update to display data from the API update.
> Api update fix

- src/app/actions/Actions.js
- src/app/components/FacetSidebar/FacetSidebar.jsx
- src/app/components/Hits/Hits.jsx
- src/app/components/Search/Search.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/app/stores/Store.js
- src/server/ApiRoutes/ApiRoutes.js
The selected facets now have a functional `[x]` removal link. When clicked, the facet should be removed and the results/facets will be updated based on the remaining keyword and selected facets.
I branched of the existing PR #39 so that one should be viewed/merged first.
> Remove facet #12

- src/app/components/FacetSidebar/FacetSidebar.jsx
- src/server/ApiRoutes/ApiRoutes.js
Fixing the date query facet search.
> Date search fix

- src/app/components/Search/Search.jsx
Removing timer animation and supporting empty searches in the Search component.
> Empty search

- src/app/components/ItemPage/EmbeddedDocument.jsx
- src/app/components/ItemPage/ItemPage.jsx
- src/app/components/Results/ResultsList.jsx
- src/client/styles/components/Item.scss
Show Hathi Trust viewer on item pages where available
Display that items are available to view on website in search results
Known issue: sometimes documents are not viewable when there's rights issues - will log for future issue
> Hathi Trust document viewer #20

- src/app/components/ItemPage/ItemPage.jsx
- src/app/components/Results/ResultsList.jsx
- src/app/utils/item.js
Changed "Place a hold" to "Request a hold" on search results page (#55)
Added Rose Main Reading Room for any location that is empty or "OFFSITE" on item page and search results page (#47)
> Copy updates, empty locations

- src/app/components/ItemPage/ItemHoldings.jsx
- src/app/components/ItemPage/ItemPage.jsx
- src/app/components/Results/ResultsList.jsx
- src/app/utils/item.js
...on the item and search results pages #65
See example by searching "Locofoco".  You should see options to "View online"
> Render electronic resources as actionable items 

- src/app/components/Application/Application.jsx
- src/app/components/Hits/Hits.jsx
- src/app/components/ItemPage/ItemDetails.jsx
- src/app/components/ItemPage/ItemPage.jsx
- src/app/components/Results/Results.jsx
- src/app/components/Search/Search.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
…ing small querying bugs, and adding a space between multiple author names.
@thisismattmiller I deployed this update to http://dev-discovery.nypl.org/. Let me know if you still find any issues.
> Item page search #84

- src/app/components/Application/Application.jsx
- src/app/components/Feedback/Feedback.jsx
- src/client/styles/components/Feedback.scss
- src/client/styles/main.scss
- src/client/styles/utils/base.scss
This adds a "Contribute feedback" button to all pages.  It currently submits via an iframe to https://docs.google.com/a/nypl.org/forms/d/e/1FAIpQLScBYFs3wFjt4kHvlEFzbmGc_jTSk_-EllRDeDelhi8Vw8MvRg/viewform
The results will go into this spreadsheet:
https://docs.google.com/spreadsheets/d/1QhVAWJaCsIm3O393qOhD4xVShlYSQwkfTpAWgJwEDHk/edit#gid=1156630791
It automatically adds the current URL of the page to the form
> Add feedback component (#93)

- src/app/components/Breadcrumbs/Breadcrumbs.jsx
- test/Application.test.js
- test/Breadcrumbs.test.js
Added unit tests for all the different cases we currently have, and then did a small code cleanup. The breadcrumb/IA will most likely change later as we've already found one IA issue. When that happens, the tests should be updated first to cover the cases. That way, they'll fail and we'll rework the code to make them pass. It's a test-driven approach which will be good to try out and perhaps give confidence to others in the workflow.
> Breadcrumbs unit testing

- package.json
- src/app/components/Hits/Hits.jsx
- test/Hits.test.js
About 80% coverage but mostly focusing on different types of unit tests, but I did try to cover different scenarios. I don't think getting 100% coverage is necessary right now and this way other components can be tested and refactored.
> Hits unit testing

- src/app/components/Hits/Hits.jsx
- src/client/styles/components/Results.scss
- Changed [x] link into button tag with text "remove"
- There's additional help text for screen readers: "remove filter [value]"
I'll have to update the unit tests. I'm gonna hold off for now since this design will likely be updated in the near future with the design refactoring.
> Make remove facet link into a button with better description #109

- src/app/components/Feedback/Feedback.jsx
Tested a local build on [Cynthia Says](http://cynthiasays.com/?) and the it met the compliance level A.
> Adding a title attribute to the feedback iframe element.

- src/app/components/Pagination/Pagination.jsx
- src/app/components/Results/Results.jsx
- test/unit/Pagination.tests.js
Broke out the code for the pagination displaying and buttons out of the Results component and into its own component. Made the `<a>` into a `<button>`.
> Pagination buttons refactor #134

- src/app/components/FacetSidebar/FacetSidebar.jsx
- src/app/components/Hits/Hits.jsx
- src/app/components/ItemPage/ItemEditions.jsx
- src/app/components/ItemPage/ItemPage.jsx
- src/app/components/Results/Results.jsx
- src/app/components/Results/ResultsList.jsx
- src/app/components/Search/Search.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/app/utils/item.js
- src/app/utils/utils.js
- test/unit/utils.test.js
Removing the axios dependency from the React components and moving the API call to a utility function. There's a default error callback function but that should be better handled.
> Axios refactor #140

- src/app/components/FacetSidebar/FacetSidebar.jsx
- src/app/components/Hits/Hits.jsx
- src/app/components/Results/Results.jsx
- src/app/components/Search/Search.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/app/utils/utils.js
- test/unit/utils.test.js
Moving code that constructs query params for sorting order and facets from components into the utility function.
Branched of `axios-refactor-#141` PR (#141) so that should be merged first.
> Refactoring URL param constructing code.

- package.json
- src/app/components/Application/Application.jsx
- src/app/components/FacetSidebar/FacetSidebar.jsx
- src/app/components/Pagination/Pagination.jsx
- src/app/components/Search/Search.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/app/utils/utils.js
- test/unit/Pagination.test.js
Searching and updating the keyword and adding/removing facets should work when clicking on the back button in the browser. A slight workaround but think it'll be more manageable with Redux.
> Browser nav #160

- src/app/components/SearchResultsPage/SearchResultsPage.jsx
Removes the functionality of grouping related bibs together and nesting them in the UI. Currently on: http://dev-discovery.nypl.org/search?q=hamilton
> Removing the collapse util call that groups related bibs together.

- src/app/components/ItemPage/ItemPage.jsx
- src/app/components/Pagination/Pagination.jsx
- src/app/components/Results/Results.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
This removes the Hathitrust viewer #188 and fixes a JS clicking bug #175 
Example of an item with a Hathitrust embedded document: http://discovery-ui-prod.us-east-1.elasticbeanstalk.com/item/b13493199
Here's the update from the PR: http://dev-discovery.nypl.org/item/b13493199
CC @jvarghese01
> Removing hathitrust viewer and fixing clicking on bib bug.

- package.json
- src/client/styles/main.scss
- webpack.config.js
Rafael showed me the light, and the light involved making these changes. Let me know if this is out o bounds.
> updates frontend to use 0.1.5 of design toolkit

- src/app/components/FacetSidebar/FacetSidebar.jsx
For #202. Edwin!!! This syntax, {\`${facet.field}-${f.value}\`}, feels so verbose -- am I being over-verbose/careful?
> Keys for facets #202

- src/app/components/FacetSidebar/FacetSidebar.jsx
- src/app/components/Hits/Hits.jsx
- src/app/components/Results/ResultsList.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
Added ability to check and uncheck a facet and make requests. #199 
This also fixes #205 
Changes are up on http://dev-discovery.nypl.org/.
**Please note: This only allows check one facet at a time.**
> Func facets #199

- src/app/components/Results/Results.jsx
- src/client/styles/components/Results.scss
Hey. This needs more work, design-wise. The API seems to be having trouble so I can't do true testing... and definitely needs to look better.
> applies design-toolkit and functionality to sort-by #195

- src/app/components/Results/Results.jsx
This PR is back with better code syntax, complying (mostly but not fully) with eslint.
> cleans up to eslint standards

- src/app/components/Pagination/Pagination.jsx
@ricardoom
Temporarily added SVGs until I get them into the React component package. Also, the latests changes in design-toolkit v0.1.10 are not in here because it's a big jump and changes the whole page . That will get updated later.
> Pagination design #201

- src/app/components/Results/Results.jsx
- src/client/styles/main.scss
> updates sortby to design-toolkit 0.10

- src/app/components/Breadcrumbs/Breadcrumbs.jsx
> adds a space in there after the greater-than sign, as mockup wants

- package.json
- src/app/components/FacetSidebar/FacetSidebar.jsx
- src/client/styles/components/FacetSidebar.scss
> 10 to 11 #228 💪 

- src/app/components/ItemPage/ItemHoldings.jsx
- src/app/components/ItemPage/ItemOverview.jsx
- src/app/components/ItemPage/ItemPage.jsx
- src/app/components/Results/ResultsList.jsx
- src/client/styles/components/Results.scss
This *begins* to integrate changes to the item pages. WIP.
> [WIP] Fresh item page

- src/app/components/Home/Home.jsx
> removes advanced search from homepage

- src/app/components/ItemPage/ItemPage.jsx
> adds omnisearch to item page

- src/app/components/FacetSidebar/FacetSidebar.jsx
This updates the style of the facets and adds a *temporary* solution to the collapse display (by not managing state). That will be subsequently updated.
> adds new facet style (collapsing shim)

- src/app/components/Search/Search.jsx
> searching again resets facets

- package.json
> bumps design-toolkit to 0.1.13

- src/app/components/FacetSidebar/FacetSidebar.jsx
Small change to add a "key" field to the datefield top-level div -- React complains with an error in the console when this is not present.
> adds key to datefields

- src/app/components/Hits/Hits.jsx
#271 
@mgiraldo can you clarify if and when these are meant to be dynamic?
> adds aria tags to results-summary

- src/app/components/FacetSidebar/FacetSidebar.jsx
> moves facet onClick and sets initial openFacet state

- src/app/components/Results/ResultsList.jsx
#282 
Could probably "clean up" more things on this page but would rather leave them in, in case they come back.
> results list should match design-toolkit template

- src/app/components/Feedback/Feedback.jsx
New form.
For future reference:
* Create a new Google Form and it's accompanying spreadsheet (for results)
* When you view the form, view its source and look for "entry." and match the entry names to the `name` attribute of your custom form element.
* Make sure that the `action` is pointing to the new google form.
> Updating feedback form to new google form file.

- src/app/utils/item.js
Tiny change to spell out Reading Room for default NYPL location #239
> spells out reading room in default location setting

- src/app/components/ItemPage/ItemPage.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
Fixes #159 
* Search results page will read "Search results".
* Item page will read Research Catalog
CC @courtneymcgee
> Adding <h1> to the search results and item page.

- src/app/components/ItemPage/ItemPage.jsx
> Removing an Item's external link to an OCLC link.

- src/app/utils/item.js
> spells out sasb in default

- src/app/components/Hits/Hits.jsx
This resolves #302 but I agree with @EdwinGuzman that we should use the React component -- although it seems to conflict with the design-toolkit at the moment. Let's patch the problem first.
> adds x svg to button

- src/app/actions/Actions.js
- src/app/components/FacetSidebar/Facet.jsx
- src/app/components/Pagination/Pagination.jsx
- src/app/components/Search/Search.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/app/stores/Store.js
- src/app/utils/utils.js
- src/server/ApiRoutes/ApiRoutes.js
This will add `search_scope=[name_of_field]` where `name_of_field` is one of the dropdown selections and query the API.
> Using search_scope API param to search by field.

- src/app/components/FacetSidebar/Facet.jsx
- src/app/components/FacetSidebar/FacetSidebar.jsx
> updates subjects to subjectLiteral

- src/app/components/FacetSidebar/DateFacet.jsx
- src/app/components/FacetSidebar/FacetSidebar.jsx
This is not quite done, but I have to leave and won't return until Monday...
I moved this out but 
- they don't work
- probably redundant code
- they show up at the top instead of in the middle of the facets
> [WIP] Date facets return

- src/app/components/ItemPage/ItemHoldings.jsx
- src/app/components/ItemPage/ItemPage.jsx
- src/app/components/Results/ResultsList.jsx
Fixes:
* #309
* #314 
* #316  (there's no author property in the API yet so it's will not display)
* #303
> Minor fixes and changes to render data correctly.

- src/app/components/FacetSidebar/DateFacet.jsx
- src/app/components/FacetSidebar/FacetSidebar.jsx
- src/app/components/Hits/Hits.jsx
- src/app/utils/utils.js
- src/server/ApiRoutes/ApiRoutes.js
> Functional dates #322

- src/app/components/ItemPage/ItemHoldings.jsx
- src/app/components/ItemPage/ItemPage.jsx
- src/app/components/Results/ResultsList.jsx
- src/app/components/Search/Search.jsx
- src/app/utils/item.js
Also updating display of online items title and link.
Fixes #286 
Probably not the best solution until we get `location` properties for bibs and items in the API. For now, it seems request links will go to the SASB form.
> Adding link to questionpoint to request items.

- appConfig.js
- src/app/components/Application/Application.jsx
- src/app/components/FacetSidebar/Facet.jsx
- src/app/components/FacetSidebar/FacetSidebar.jsx
- src/app/components/Home/Home.jsx
- src/app/components/ItemPage/ItemDetails.jsx
- src/app/components/ItemPage/ItemHoldings.jsx
- src/app/components/ItemPage/ItemPage.jsx
- src/app/components/Results/ResultsList.jsx
- src/app/components/Search/Search.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/app/utils/utils.js
- src/server/ApiRoutes/ApiRoutes.js
- src/server/ApiRoutes/itemSearch.js
Lots of small changes (including markup cleanup) here and there.
Should fix #325 by adding a spinner and #310 by adding default facet object and also removing code we don't need. Also, displaying the date in the search results.
> Data review refactor

- src/app/components/ItemPage/ItemPage.jsx
> adds additional metadata

- src/app/components/ItemPage/ItemHoldings.jsx
- src/app/components/Results/ResultItems.jsx
- src/app/utils/item.js
For #331, see context there and comment with design/display opinions. We can also adjust later.
> checks availability status and shows accessMessage

- .ebextensions/01_loadbalancer-terminatehttps.config
- src/app/components/Application/Application.jsx
- src/app/components/FacetSidebar/DateFacet.jsx
- src/app/components/FacetSidebar/Facet.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/app/utils/item.js
- src/app/utils/utils.js
- src/server/ApiRoutes/ApiRoutes.js
Should mostly fix #293 . The `01_loadbalancer...` file got into this PR but it's needed to deploy to the prod AWS account. It's safe (and necessary) to be in git.
> Multiple facets#293

- src/app/components/Application/Application.jsx
- src/app/components/FacetSidebar/DateFacet.jsx
- src/app/components/FacetSidebar/Facet.jsx
- src/app/components/ItemPage/ItemPage.jsx
- src/app/components/Results/ResultsList.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/app/utils/item.js
- src/app/utils/utils.js
- src/server/ApiRoutes/ApiRoutes.js
Fixes #330, #329, #328. Also fixes #293  a bit.
> Misc fixes

- src/client/styles/utils/base.scss
Resolves #319 -- Thinking this be reviewed and cleaned up more generally..?
> removes hover class from button base css

- package.json
- src/client/App.jsx
- webpack.config.js
> Adding babel polyfill.

- src/app/components/Pagination/Pagination.jsx
- src/app/components/Search/Search.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/app/utils/utils.js
- src/server/ApiRoutes/ApiRoutes.js
Part fix of #320 
Other fixes include better page searching and general component refactoring.
> component refactoring and fixing small searching bugs.

- src/app/components/Pagination/Pagination.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/app/components/Sorter/Sorter.jsx
- src/app/utils/utils.js
- src/server/ApiRoutes/ApiRoutes.js
@ablwr I'm introducing a big change into how the API query is being generated. Instead of generating it in each component, I want to create a utility function that is used at the top level of the application, in `SearchResultsPage` and it will trickle down to children components. There's documentation on the function in `utils.js`. Let me know what you think and if it makes sense. So far only the `Pagination` and the `Sorter` components are using it but I want all components to use it. It'll reduce code and make debugging easier.
> Component refactor 2

- package.json
- server.js
- src/app/components/Application/Application.jsx
- src/app/components/Home/Home.jsx
- src/app/components/ItemPage/ItemPage.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
> Title time

- src/app/components/Hits/ClearHits.jsx
- src/app/components/Hits/Hits.jsx
This adds "Clear current search query, filters, and sorts" and a clearResults function -- although doesn't solve the problem of lingering facet tabs after search has been reset. (Which is present when you call for a new search, too).
> adds clear query / reset

- src/app/components/Breadcrumbs/Breadcrumbs.jsx
This does what it says (for #361) but it's super verbose/not-DRY. @EdwinGuzman can we talk about how you recommend refactoring this? This whole component could use an overhaul, probably...
> adds accessibility support for breadcrumbs

- appConfig.js
- src/app/actions/Actions.js
- src/app/components/FacetSidebar/DateFacet.jsx
- src/app/components/FacetSidebar/Facet.jsx
- src/app/components/FacetSidebar/FacetSidebar.jsx
- src/app/components/Hits/Hits.jsx
- src/app/components/ItemPage/ItemPage.jsx
- src/app/components/Search/Search.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/app/stores/Store.js
- src/app/utils/utils.js
- src/server/ApiRoutes/ApiRoutes.js
Fixes #362 - hopefully. May be other bugs but selecting multiple values from each facet now works.
I'll give it another go at refactoring and cleaning if this first step works.
> Multi values #362

- src/app/components/Breadcrumbs/Breadcrumbs.jsx
- src/app/components/ItemPage/ItemPage.jsx
- src/app/utils/utils.js
Fixes #81 .
On an item page, it will say
`Home > Research > Research Catalog > Search Results > Ken Dewey collection, (bulk 1959-1972).`
`Search Results` will go to the search results page.
> Facet routing #81

- README.md
> contributing rule/reminder

- src/app/utils/utils.js
> checks for materialType and adds _packed if true

- src/app/components/Hits/Hits.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/app/stores/Store.js
- src/server/ApiRoutes/ApiRoutes.js
- src/server/ApiRoutes/itemSearch.js
Fixes #387 .
@kfriedman , is it right to check for error status > 400?
This will display the following. To test locally, mess around with the API endpoint in `appConfig.js`.
> Adding error object from API to the front end to display querying error.

- src/app/components/ItemPage/ItemPage.jsx
With all the key-value pairs. #397
> adds all data and also top-level preview

- src/app/components/ItemPage/ItemHoldings.jsx
In addition to above... I tested for this.props.itemId and it seems to be working -- but should I return the message and revert? LMK!
> shows table with four main fields, temporarily

- src/client/styles/components/Facets.scss
- src/client/styles/main.scss
> Adding back the hiddenFacet class to hide facets.

- src/app/components/FacetSidebar/Facet.jsx
- src/app/components/FacetSidebar/FacetSidebar.jsx
- test/unit/Facet.test.js
This PR is to add new facet "Owning Location/Division" and updates the name of the facet "Format", both based on the task [JIRA DIS-5](https://jira.nypl.org/browse/DIS-5) and github task [373](https://github.com/NYPL-discovery/discovery-front-end/issues/373)
> 373 update facets

- src/app/components/BibPage/BibPage.jsx
Fixes #418 .
Temporarily displaying the link at the top of the page.
> Constructing and displaying MARC record for a bib.

- src/app/components/FacetSidebar/DateFacet.jsx
- src/app/components/FacetSidebar/Facet.jsx
- src/app/components/Hits/Hits.jsx
- src/app/components/Pagination/Pagination.jsx
- src/app/components/Results/ResultsList.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/app/components/Sorter/Sorter.jsx
- src/client/styles/main.scss
Fixes #391 and #390 .
Also,
* Updates all `svg` DOM elements to use icons from `dgx-svg-icon` package,
* Add back code that was somehow previously lost.
> Random cleanup

- src/app/components/Search/Search.jsx
- src/app/utils/utils.js
- src/server/ApiRoutes/ApiRoutes.js
- src/server/ApiRoutes/Search.js
Fixes #409 
Turn JS off in your browser and make searches. Use the drop down to select Title, Subject, Author, etc.
@wlla @seanredmond can you also QA please? There may be other things that don't work like selecting facets or removing a selected facet. For now, this only fixes the search bar. THANKS!
http://dev-discovery.nypl.org/
> Search no js

- src/app/components/BibPage/BibDetails.jsx
Removes the unnecessary based on the request from [DIS-58](https://jira.nypl.org/browse/DIS-58)
> Removed unnecessary fields of a bib.

- src/app/components/HoldRequest/HoldRequest.jsx
- src/client/styles/components/HoldPage.scss
Fixes #452 
On a Hold Request page:
@ricardoom
> Making delivery location on hold request page radio options.

- src/app/components/FacetSidebar/Facet.jsx
- src/app/components/FacetSidebar/FacetSidebar.jsx
- src/app/components/Search/Search.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/app/utils/utils.js
- src/server/ApiRoutes/Search.js
I added a temporary "Search" button for the no-js situation:
It'll only appear when JS is turned off. You should now be able to select multiple facets and then click on the "Search" button. I believe in the future it will be "APPLY". Regardless, it'll work the same way. This is also very preemptive of the future design but should help with a11y in any case.
This is up on [dev-discovery.nypl.org](http://dev-discovery.nypl.org/)
@seanredmond @wlla @ricardoom please review too.
> No js facets

- src/app/components/Item/ItemHoldings.jsx
> Fixing pagination when it was breaking for a bib page.

- CHANGELOG.md
- package.json
Hey, this is for New Sprint 2 updates. Let me know if I should include anything else in the CHANGELOG for either this new tag or any previous tags. Tag names are arbitrary but trying to make it reflect all the changes we've done for each sprint/tag.
> Changes needed for new version.

- src/app/components/HoldRequest/HoldRequest.jsx
- test/unit/HoldRequest.test.js
This PR adds the data check so the tests will be passed now.
> Fix hold request test

- src/app/components/HoldPage/HoldConfirmation.jsx
This PR updates the function to render the location information for error data fallbacks.
> Fix hold confirmation test

- src/app/components/ElectronicDelivery/ElectronicDelivery.jsx
- src/app/components/ElectronicDelivery/ElectronicDeliveryForm.jsx
- src/app/components/HoldRequest/HoldRequest.jsx
- src/client/styles/components/ElectronicDeliveryForm.scss
- src/client/styles/main.scss
- src/server/ApiRoutes/ApiRoutes.js
- src/server/ApiRoutes/Hold.js
Fixes #480 
This is just a dummy skeleton form but the form submits both on the client and server side and captures data. I added comments to the dummy functions where the gathered data should be manipulated and used with the Request API endpoint (which we don't have yet).
> Edd skeleton form

- src/app/components/BibPage/BibDetails.jsx
- src/app/components/BibPage/BibMainInfo.jsx
- src/app/components/BibPage/BibPage.jsx
- src/app/components/Item/ItemHoldings.jsx
- src/client/styles/style-v2.scss
Um, hesitant to do more work here, as it seems like the item page is changing again and that changes the way we render these details. Things are somewhat "hardcoded" due to, I think you'll see, the way some fields are actually a combination of many fields. 
But: Should I just scrap this work and wait?
Should I work on extending the BibDetails component instead to be able to handle different values, and render both the top and bottom details from the same component? I think we used to do things that way, many iterations ago.
> Refactoring bib page

- src/app/components/BibPage/BibDetails.jsx
- src/app/components/BibPage/BibMainInfo.jsx
This refactors the BibMainInfo to be more like BibDetails -- a lot like it, in fact, although a bit minimal. Not sure what code should be erased completely and which will come back. This brings us up to the current design with minimal fields, until we get the final say and we can scale up accordingly! 💪
> BibMainInfo refactor

- src/app/components/ElectronicDelivery/ElectronicDeliveryForm.jsx
OK, this is for updating #496 as requested. :)
> removes required alert for date and volume in EDD

- src/app/components/FacetSidebar/FacetSidebar.jsx
The PR solve [issue 460](https://waffle.io/NYPL-discovery/discovery-general/cards/5954ddb552e02c018c290567).
> Removed the location filter.

- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/app/components/Sorter/Sorter.jsx
- src/app/utils/utils.js
- src/server/ApiRoutes/Search.js
The PR is to make sorting to work without js. The main changes include changing the DOM to <select> and the adding more logic for the function `searchServerPost` in `Search.js` to take sort arguments.
The design is not the focus for the PR though.
> 411 no js sort by

- src/app/components/SearchResultsPage/SearchResultsPage.jsx
This PR removes <Hits> and related props.
> Remove hit

- src/app/components/ElectronicDelivery/ElectronicDeliveryForm.jsx
- src/app/utils/formValidationUtils.js
This loosens the requirements fields to just require name and email, and adds a note field.  #505
> adds note fields and removes requirements for most fields

- src/app/components/BibPage/BibDetails.jsx
- src/app/components/BibPage/BibMainInfo.jsx
- src/app/components/BibPage/BibPage.jsx
Still working out some issues with the content and the relation to the API, but this gets things up to speed and better to show for demo.
> Bib page with new content

- src/app/components/BibPage/BibDetails.jsx
- src/app/components/BibPage/BibPage.jsx
- src/app/components/Item/ItemTableRow.jsx
- src/app/components/Search/Search.jsx
- src/client/styles/main.scss
- src/client/styles/style-v2.scss
Should look like [mockup](https://nypl.github.io/design-toolkit/discovery-item.v2.html) and use most recently toolkit shim available. Content is still pending. DIS-68.
> gets bib page in agreement with current mockup, pending content

- package.json
> Bumping up version of design-toolkit.

- src/views/index.ejs
Fixes validation error (`<script>` should be a child of `<body>`)
> Move script tags within body tag

- src/app/components/BibPage/BibDetails.jsx
- src/app/components/BibPage/BibMainInfo.jsx
> Removing the title attribute from links on the bib page.

- src/app/components/Item/ItemTable.jsx
> Adding scope='col' to table headers.

- src/app/components/BibPage/BibPage.jsx
Fixes #524 
Link to test: http://dev-discovery.nypl.org/bib/b10710345
> Not rendering the back link if the page was hit directly.

- src/app/components/ElectronicDelivery/ElectronicDelivery.jsx
- src/app/components/HoldRequest/HoldRequest.jsx
- src/app/utils/item.js
- src/server/ApiRoutes/ApiRoutes.js
- src/server/ApiRoutes/Hold.js
Making a PR for this now even though we are still testing it. @ktp242 I will wait until your EDD request PR is merged in and then I will update my PR, since that caused a few merge conflicts when we try to deploy `dev-eb-deploy`.
> Nypl source data

- src/app/components/Results/ResultsList.jsx
> Remove items available message

- src/app/components/HoldConfirmation/HoldConfirmation.jsx
This PR updates the copy of the confirmation page.
based on this mock up,
https://app.moqups.com/digitalrepository@nypl.org/55BjtB7Pm0/view/page/a0f66a95b
> Update confirmation page copy

- src/server/ApiRoutes/Hold.js
Solve issue [560](https://github.com/NYPL-discovery/discovery-front-end/issues/560)
> Added data check for the response from delivery location API.

- src/app/components/BibPage/BibPage.jsx
- src/app/components/Item/ItemHoldings.jsx
- src/app/components/Item/ItemTable.jsx
- src/app/components/Results/ResultsList.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
Fixes #517 (check axe)
I think the problem was that the ids that the `aria-controls` was pointing to did not exist. Updated it to have the correct element now.
> Fixing some aria attributes.

- appConfig.js
- package.json
- server.js
- src/app/components/Application/Application.jsx
- src/app/components/BibPage/BackLink.jsx
- src/app/components/BibPage/BibDetails.jsx
- src/app/components/BibPage/BibMainInfo.jsx
- src/app/components/ElectronicDelivery/ElectronicDelivery.jsx
- src/app/components/HoldConfirmation/HoldConfirmation.jsx
- src/app/components/HoldRequest/HoldRequest.jsx
- src/app/components/Home/Home.jsx
- src/app/components/Item/ItemHoldings.jsx
- src/app/components/Item/ItemTableRow.jsx
- src/app/components/Pagination/Pagination.jsx
- src/app/components/Results/ResultsList.jsx
- src/app/components/Search/Search.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/app/components/Sorter/Sorter.jsx
- src/app/routes/routes.jsx
- src/client/App.jsx
- src/server/ApiRoutes/ApiRoutes.js
- src/server/ApiRoutes/Hold.js
- src/server/ApiRoutes/Search.js
- src/views/index.ejs
Fixes #515.
This a pretty big PR.
* Added a `baseUrl` to the app's config file.
* Updated `history` npm package to a more stable version that matches the version of React-Router.
* Server side changes:
* Make updates for the Express app to read the correct routes and make correct redirects (that work in the no-js scenario).
* Updated the path to the js and css minified files.
* Created react-router routes for the server side.
* Client side changes:
* Updated `<Link>`'s `to` attribute.
* Added react-router basename url.
* Created react-router routes for the client side.
> Url reverse proxy

- src/app/components/ElectronicDelivery/ElectronicDelivery.jsx
- src/app/components/ElectronicDelivery/ElectronicDeliveryForm.jsx
- src/app/utils/formValidationUtils.js
- src/client/styles/main.scss
Content should be up to date with latest mentioned in the issue... https://github.com/NYPL-discovery/discovery-front-end/issues/494#issuecomment-317835778
And should raise up to the top level.
This could probably use a style treatment but we don't have that at the moment (should probably be shaped within the toolkit), so I just did the minimal to make it red like the others.
> Edd error form content

- package.json
- src/client/styles/style-v2.scss
This PR updates toolkit to v1.0.22. Also there's a piece of css rules causes issues so it is removed. Also include @ricardoom
> Updated toolkit and removed unnecessary styles.

- locations.js
- src/app/components/HoldRequest/HoldRequest.jsx
- src/server/ApiRoutes/Hold.js
This PR updates the delivery location names to a more user friendly format, based on content team's request.
> Update data sheet and location names

- src/app/components/BibPage/BibDetails.jsx
Fixes #563 - If there's only once value in the field, then it will be a simple data display, if it's multiple values then it will display as a list of those values. Only `Subject` should have linkable values. `Publisher` is made up of three fields so it gets its own special function.
Note: Not displaying the following
* Link to Electronic Resource
* Notes
* Bibliography
* GPO
* Other Titles
* Owning Institution
`getDefinitions` and `getDefinitionsObject` are very similar functions, but I'd like to refactor those two later.
> Below fold data

- src/app/components/HoldConfirmation/HoldConfirmation.jsx
This is PR just adds a new off-site info link based on the updated mock up.
https://app.moqups.com/digitalrepository@nypl.org/55BjtB7Pm0/view/page/a0f66a95b
> Added off-site info link.

- src/app/components/Home/Home.jsx
New home page design. Fixes #567
> Update home page

- src/app/components/HoldConfirmation/HoldConfirmation.jsx
This PR updates the DOM of confirmation page and integrates with the new version of design. @ricardoom
> Implement confirmation page design

- src/app/components/Search/Search.jsx
> Removing some fields from the search dropdown.

- src/app/components/HoldRequest/HoldRequest.jsx
Fixes #468
Example: http://dev-discovery.nypl.org/research/collections/discovery-beta/hold/request/b17193733-i22971642
> Updating design for the Hold Request page.

- src/app/components/Home/Home.jsx
Fixes #607, my own spelling error.
> Spell 'presentation' correctly

- DEPLOYMENT.md
- README.md
QA!
Fixes #598 
So now we should merge `development` into `qa` and then `qa` into `master`. It's a workflow some of us have done before but haven't done for this repo. I wrote down documentation on deployment to the QA environment and git workflow. I added everyone who has helped so far for a heads up.
> Adding documentation on the QA environment and branch for deployment.

- src/app/components/Results/ResultsList.jsx
- src/app/components/Sorter/Sorter.jsx
- src/client/styles/components/design-toolkit-updates.scss
Fixes #601 and #609 
* General overview of the Search Results a11y by fixing some input/label and foreground/background color issues.
* Have not done anything with aria-live for this PR for the updated search results.
* Fixed duplicate IDs in the item table.
> Search results a11y review

- appConfig.js
> Updating app url.

- src/app/components/ElectronicDelivery/ElectronicDeliveryForm.jsx
- src/app/utils/formValidationUtils.js
This PR updates the accepted input value to be a string for the start page field and end page field.
> Changed the format of the fields of start page and end page to string.

- src/app/components/HoldConfirmation/HoldConfirmation.jsx
This PR updates the hold delivery location to its short name instead of the abbreviation.
> Updates the hold delivery location to its short name instead of the abbreviation

- src/app/components/BibPage/BibDetails.jsx
- src/app/components/Item/ItemTableRow.jsx
- src/app/utils/item.js
First pass to fix #622 
Need to test different bibs. Check [DIS-104](https://jira.nypl.org/browse/DIS-104) for more information. Followed the flowchart logic as best as I could.
> Displaying status for non-recap nypl items.

- appConfig.js
- src/app/components/BibPage/BibPage.jsx
- src/app/components/Breadcrumbs/Breadcrumbs.jsx
- src/app/components/ElectronicDelivery/ElectronicDelivery.jsx
- src/app/components/HoldConfirmation/HoldConfirmation.jsx
- src/app/components/HoldRequest/HoldRequest.jsx
- src/app/components/Home/Home.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
This PR updates the title to `Shared Collection Catalog` on each page and the breadcrumbs component. It also adds the missing title on EDD form page.
> Update app title everywhere

- src/client/styles/main.scss
- src/client/styles/utils/base.scss
Fixes #650 
On http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/
> Adding quick footer fixes.

- src/app/components/HoldRequest/HoldRequest.jsx
- src/app/components/Search/Search.jsx
- src/app/components/Sorter/Sorter.jsx
- src/server/ApiRoutes/ApiRoutes.js
Fixes #635 
Some `<form>`'s action attribute did not have the updated base URL included in the endpoint. Therefore POSTs were not working. They should be okay now -> turn off JS and try searching, sorting, and submitting a physical (ONLY) hold request.
> Adding app url to form for correct POST routing endpoints.

- src/app/components/Search/Search.jsx
> Updating the omnisearch's fieldset to a div.

- src/app/components/ElectronicDelivery/ElectronicDeliveryForm.jsx
- src/app/utils/formValidationUtils.js
Fixes #663 .
Updated the page error fields to display individually for each input field. Try out http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/hold/request/b16295746-i15610118/edd.
Also updated the `aria-labelledby` values.
> Updated edd page errors

- README.md
Fixes #451 
I think this will keep us on our toes about what we need to work on.
> Adding badges. YAY

- src/app/utils/formValidationUtils.js
> Updating the page input error message in the EDD form.

- src/app/components/HoldRequest/HoldRequest.jsx
- src/server/ApiRoutes/Hold.js
This PR updates the error message on HoldRequest page.
> Hold request page error

- CHANGELOG.md
- README.md
- package.json
@ktp242 want to add anything else? By the way, I'm removing the `v` from the version so that it's better semantically and other apps can pick it up from package.json.
> README update to 0.7.0

- src/app/components/ElectronicDelivery/ElectronicDeliveryForm.jsx
> EDD - Updating the required attribute in input fields to aria-required.

- README.md
- src/app/components/NotFound404/NotFound404.jsx
- src/app/routes/routes.jsx
- test/unit/NotFound404.test.js
Fixes #702
On dev, try:
* http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/sarch?q=hamlet
* http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/this-is-a-fake-url
* http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/hold/request/doesnotexist
> Adding 404 page and including tests.

- README.md
This PR adds the instruction about alarm and metric. It offers the link to engineering-general repo.
> Added setting up alarms instruction on README.

- log/discovery-ui.log
- src/app/components/Item/ItemTableRow.jsx
Fixes #654 .
Eh, ignore the log file, committed it by accident.
> Adding an empty space in the item table cell if the data is not available.

- src/app/components/ElectronicDelivery/ElectronicDelivery.jsx
This PR updates EDD page's header based on the issue #684  
on dev now
http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/hold/request/b18154904-i11039841/edd
> Updated new header for EDD page.

- src/app/components/BibPage/BibDetails.jsx
- src/app/components/BibPage/BibPage.jsx
> Updating 'publisher' to 'publication'.

- src/app/utils/item.js
Fixes #726.
CUL/PUL items should now have `Offsite` as its location.
> Default item loc

- README.md
- appConfig.js
- package.json
Fixes #744. Deployed to dev and it's working. I set the environments variables in EBS so I just need to deploy now.
> Adding the production API environment.

- src/app/components/Breadcrumbs/Breadcrumbs.jsx
- src/app/components/ResultsCount/ResultsCount.jsx
- test/unit/Breadcrumbs.test.js
- test/unit/Facet.test.js
- test/unit/Hits.test.js
- test/unit/NotFound404.test.js
- test/unit/ResultsCount.test.js
- test/unit/SearchButton.test.js
Fixes #757.
Tests for `Breadcrumbs` and `ResultsCount`. Please choose some components and write/update tests @ktp242 .
> Misc tests 1

- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- test/unit/HoldConfirmation.test.js
- test/unit/NotFound404.test.js
- test/unit/SearchButton.test.js
- test/unit/SearchResultsPage.test.js
Fixes #759
Writing tests for the `SearchButton` and the `SearchResultsPage` components.
> Search tests

- test/unit/Home.test.js
> Updating tests for the homepage.

- src/app/components/BibPage/BibDetails.jsx
- src/app/components/BibPage/DefinitionList.jsx
Fixes #781
Examples: http://dev-discovery.nypl.org/research/collections/shared-collection-catalog/bib/b18539100
vs
https://www.nypl.org/research/collections/shared-collection-catalog/bib/b18539100
> Updating logic for the publication.

- src/app/components/BibPage/BibPage.jsx
> Removing linked title from the bib page.

- src/client/App.jsx
- src/views/index.ejs
Fixes #793.
Small update to change the Google Analytics ID. CC @seanredmond
> Updating analytics id. Small metatag update.

- src/app/components/HoldConfirmation/HoldConfirmation.jsx
> Updating Hold Confirmation copy.

- src/app/components/Results/ResultsList.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- test/unit/ResultsList.test.js
Fixes #796 
Got to 82% I think.
> Tests results list

- package.json
- src/app/components/LoadingLayer/LoadingLayer.jsx
This PR implements the focus trap for the loading layer. On dev now.
> Added focus trap to the loading layer.

- src/app/components/HoldRequest/HoldRequest.jsx
- test/unit/HoldRequest.test.js
This PR is for updating the tests for <HoldRequest>. Now is 64% coverage. I think I should make a PR first and I will improve it after I am back! Thanks for the help!
> Added tests.

- README.md
- package.json
- webpack.config.js
> Adding information on webpack-bundle-analyzer.

- test/unit/Alt.test.js
> Updating tests for alt actions and store.

- src/app/components/Sorter/Sorter.jsx
- test/unit/ResultsList.test.js
- test/unit/Sorter.test.js
> Test sorter

- src/app/components/Search/Search.jsx
- src/app/components/Sorter/Sorter.jsx
- test/unit/ResultsList.test.js
- test/unit/Search.test.js
- test/unit/Sorter.test.js
> Test search

- src/app/components/FilterPopup/FilterPopup.jsx
- src/app/components/Filters/FieldsetDate.jsx
- src/app/components/Filters/FieldsetList.jsx
- src/app/components/Filters/SelectedFilters.jsx
- src/server/ApiRoutes/Search.js
- test/unit/FieldsetDate.test.js
- test/unit/FilterPopup.test.js
https://jira.nypl.org/browse/DIS-158
This PR adds the function of "Clear Filters" button to clear all the selected filters in the state and on the UI. Along with the test.
On dev now.
One thing to be noted is that the tests for "FieldsetDate" will be failed now due to the updates for the function of this PR as the old data format of "FieldsetDate" does not fit anymore. The following up PR will be handling this issue.
> Clear filters button

- src/app/components/Filters/SelectedFilters.jsx
- src/app/utils/utils.js
- test/unit/SelectedFilters.test.js
- test/unit/utils.test.js
Fixes #853  and finishes a bit more JIRA ticket [DIS-162](https://jira.nypl.org/browse/DIS-162).
> Date filter api

- package.json
- src/app/components/FilterPopup/FilterPopup.jsx
- src/app/components/Filters/FieldsetDate.jsx
- src/app/components/Filters/FieldsetList.jsx
- src/app/components/ResultsCount/ResultsCount.jsx
- src/client/styles/components/FilterPopup.scss
- src/server/ApiRoutes/Search.js
- test/unit/FieldsetDate.test.js
- test/unit/FilterPopup.test.js
- test/unit/ResultsCount.test.js
Needs more polishing but check it out on dev. Made a PR just to see the differences in SCSS files.
> Design toolkit filter popup

- DEPLOYMENT.md
This PR updates the readme for deployment.
> Updated the readme for deployment.

- src/app/components/ElectronicDelivery/ElectronicDelivery.jsx
- src/app/components/FilterPopup/FilterPopup.jsx
- src/app/components/Filters/FieldsetDate.jsx
- src/client/styles/components/FilterPopup.scss
- test/unit/FieldsetDate.test.js
This PR improves the error messages, both inline or aggregated, for date filters. The update styles should fit our convention now. On dev.
> Error message improvement

- package.json
- src/app/components/FilterPopup/FilterPopup.jsx
- src/app/components/Filters/FieldsetDate.jsx
- src/app/components/Filters/FieldsetList.jsx
- src/client/styles/components/FilterPopup.scss
- test/unit/FilterPopup.test.js
This PR updates the toolkit, DOMs, and fixes some minor styles. On dev.
> Update toolkit 0.1.26.3

- src/app/components/FilterPopup/FilterPopup.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/server/ApiRoutes/Search.js
This PR updates error message block for date input filed errors.
> Server side error message

- CHANGELOG.md
- package.json
Update the header to version 2.1.1
> Updated the header to version v2.1.1

- CHANGELOG.md
- package.json
- src/client/App.jsx
- src/views/index.ejs
This PR updates degx-react-ga related functions based on the updates.
> Update dgx react ga related functions

- src/app/components/Filters/FieldsetDate.jsx
- src/app/components/Filters/FieldsetList.jsx
> Updating filter form legends to also be h3s

- src/app/components/FilterPopup/FilterPopup.jsx
- src/client/styles/components/FilterPopup.scss
- src/client/styles/components/SelectedFilters.scss
> Error state date

- src/app/components/FilterPopup/FilterPopup.jsx
- src/app/components/Filters/FieldsetDate.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/app/utils/utils.js
- src/client/styles/components/FilterPopup.scss
- src/client/styles/components/SelectedFilters.scss
- src/client/styles/components/Sorter.scss
- test/unit/FilterPopup.test.js
This updates the layout and style of the filter form and all the buttons. CSS cleanup as well.
> Nth filters update

- src/app/components/FilterPopup/FilterPopup.jsx
Fixes #910 - Focus on the first "clear filters" button when the dropdown opens.
Up on dev-discovery.
@wlla does the first "clear filters" button sound like a good candidate?
> Focus on clear filters btn when the dropdown is opened.

- src/app/components/FilterPopup/FilterPopup.jsx
- src/client/styles/components/FilterPopup.scss
Converted the filter dropdown action row into a list of buttons:
Added `aria-label`s, too, which will get refined later on.
Check it out on dev-discovery.
> Updating the filter action row to be a list of buttons.

- src/app/components/FilterPopup/FilterPopup.jsx
- src/client/styles/components/FilterPopup.scss
- src/client/styles/components/Sorter.scss
- test/unit/FilterPopup.test.js
Fixes #918 
Trying to make the filter modal workout when javascript is turned off. Style-wise, closely but not precisely, looks the same as when js is on. Functionality-wise, all the buttons should work as when js is turned on. Please check on dev-discovery.
Also, moved all the buttons inside the form so that it conforms to better semantic DOM layout (since the buttons should submit the form) CC @wlla .
> No js filter redo

- src/app/components/FilterPopup/FilterPopup.jsx
- src/client/styles/components/FilterPopup.scss
> Adding logic check to make sure that dates are not beyond current year.

- package.json
- src/app/components/FilterPopup/FilterPopup.jsx
- src/app/components/Home/Home.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/client/styles/components/FilterPopup.scss
- src/client/styles/components/SelectedFilters.scss
- src/client/styles/components/Sorter.scss
- test/unit/SearchResultsPage.test.js
This PR adds `DIV`s to the DOM for the filter dropdown.
It also fixes the design issue where the action button borders need to extend the full width of the page. Took the liberty to align left the three action buttons in the form in mobile. A lot of other CSS to override and make use of existing classes. More divs.
> Updating the DOM for the filter form action buttons so that they go full width.

- src/app/components/FilterPopup/FilterPopup.jsx
- src/app/components/Filters/SelectedFilters.jsx
Fixes #923 - Only added events related to filters.
Check out spreadsheet https://docs.google.com/spreadsheets/d/1e-U8-pW0NKbZT2o-HkHiPHyv-R9CCORsnZu3xsD-1xk/edit#gid=0
This is hard to verify in production mode (any deployed instance). You can checkout the branch and the events will automatically print to the console. Just a few examples:
> Adding GA events to all filter related actions.

- src/app/components/Filters/SelectedFilters.jsx
- src/client/App.jsx
- src/client/styles/components/SelectedFilters.scss
- test/unit/SelectedFilters.test.js
Removing the "clear filters" button outside of the selected filters list.
> Moving the clear filters button outside of the selected filters list.

- src/app/components/HoldRequest/HoldRequest.jsx
- test/unit/HoldRequest.test.js
This was a previous PR that was initially set to be merged into the Filters update. But, wanted to extract it in case it's ready to be deployed to production.
@katesweeney fyi for [SCC-207](https://jira.nypl.org/browse/SCC-207)
> Checking to see if a bib is really available before processing to request page.

- src/app/components/Buttons/SearchButton.jsx
- src/app/components/FilterPopup/FilterPopup.jsx
- src/app/components/Filters/SelectedFilters.jsx
- src/app/components/LoadingLayer/LoadingLayer.jsx
- src/app/components/ResultsCount/ResultsCount.jsx
- src/app/components/Search/Search.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- test/unit/FilterPopup.test.js
- test/unit/ResultsCount.test.js
- test/unit/SearchResultsPage.test.js
This fixes #956 and #954 
This is an update from PR #953 which more or less failed.
> Aria live try2

- package.json
- src/views/index.ejs
* Updating header to 2.4.7.
* Adding OptinMonster script.
On dev - http://dev-discovery.nypl.org/
> Updating header to 2.4.7 and adding optinmonster.

- CHANGELOG.md
- package.json
Updating the Header and Footer npm versions. Up on dev: http://discovery-ui-development.us-east-1.elasticbeanstalk.com/research/collections/shared-collection-catalog/
Footer icons are now SVG icons.
> Updating the header and footer versions.

- DEPLOYMENT.md
Added notes to "ideal workflow" about what needs to be updated and when
and where to bump an app version.
> Add clarity around how/when to version releases

- .ebextensions/01_loadbalancer-terminatehttps.config
- .travis.yml
- CHANGELOG.md
- package-lock.json
- package.json
- src/app/components/BibPage/Tabbed.jsx
Better skip nav, focus outline, focusable attribute on footer svgs.
CC @danamansana FYI, I fixed some eslint issues in the `Tabbed` component.
> Updating versions of header and footer.

- .ebextensions/01_loadbalancer-terminatehttps.config
- CHANGELOG.md
- package.json
- src/app/components/ElectronicDelivery/ElectronicDeliveryForm.jsx
- src/app/components/HoldRequest/HoldRequest.jsx
- test/unit/HoldRequest.test.js
Light edits per [SCC-1211](https://jira.nypl.org/browse/SCC-1211)
> [KK] Minor text tweaks to EDD form and supporting test.

- CHANGELOG.md
- README.md
- package.json
- src/app/components/HoldRequest/HoldRequest.jsx
This should pull the updated header package into qa
> Merge development into qa

- src/app/components/HoldRequest/HoldRequest.jsx
Holiday message for Christmas 2018 through to New Year.
> Adding 2018 December holiday message

- CHANGELOG.md
- README.md
- appConfig.js
- package.json
- server.js
- src/app/components/Application/Application.jsx
- src/app/components/BibPage/BibDetails.jsx
- src/app/components/BibPage/DefinitionList.jsx
- src/app/components/BibPage/Tabbed.jsx
- src/app/components/FilterPopup/FilterPopup.jsx
- src/app/components/Filters/SelectedFilters.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/app/routes/routes.jsx
- src/app/stores/Store.js
- src/app/utils/subjectFilterUtils.js
- src/app/utils/utils.js
- src/client/App.jsx
- src/server/ApiRoutes/Search.js
- test/unit/FilterPopup.test.js
- test/unit/SelectedFilters.test.js
- test/unit/subjectFilterUtil.test.js
- test/unit/utils.test.js
This branch contains all the changes I've been working on to do with filters and navigation, and supersedes the other PR's, which I have closed. It:
1) Changes history listening to listen to App's appHistory. This fixes some navigation issues.
2) Updates the page when making ajax calls, fixing a bug where the announced page got out of sync with the displayed page
3) Adds subject filter buttons when filtering by subject
4) Adds filter updating to the BibPage newSearch method, so that the filters displayed in the dropdown menu are correctly scoped to the subject we are searching in
5) Separates out subject filters from other filters so they will be displayed when the dropdown is open.
The following issues still exist:
1) There is probably a better way of passing the appHistory EDIT: I've …
> Subject filters and navigation fix

- src/app/components/SubjectHeading/SubjectHeadingShow.jsx
- src/app/components/SubjectHeading/SubjectHeadingsList.jsx
- src/app/models/Range.js
Fixes the truncation logic on the show page
> Show truncation

- src/app/components/SubjectHeading/SubjectHeading.jsx
- src/app/components/SubjectHeading/SubjectHeadingsContainer.jsx
Makes a couple of small changes to match ui with backend changes.
> Realign ui and api

- src/app/components/SubjectHeading/SubjectHeadingsContainer.jsx
- src/app/components/SubjectHeading/SubjectHeadingsList.jsx
- src/app/models/Range.js
Also includes some changes that were recommended in code walkthrough to do with simplifying Range.
> Filtered index

- src/app/components/SubjectHeading/SortButton.jsx
- src/app/components/SubjectHeading/SortButtons.jsx
- src/app/components/SubjectHeading/SubjectHeading.jsx
- src/app/components/SubjectHeading/SubjectHeadingShow.jsx
- src/app/components/SubjectHeading/SubjectHeadingShowWrapper.jsx
- src/app/components/SubjectHeading/SubjectHeadingsList.jsx
- src/app/models/Range.js
- src/client/styles/components/SubjectHeadings.scss
Adds sort buttons. At least two issues 1) Styling problems (the show page is getting very cramped in general, so this might be part of a bigger restyling issue) 2) Modifying props instead of state is probably a bad idea...
> Sort buttons

- src/app/components/SubjectHeading/SubjectHeadingPageWrapper.jsx
- src/app/components/SubjectHeading/SubjectHeadingsContainer.jsx
Adds button to filtered index pages to return results sorted by bib/descendant count
> Sort indices

- src/app/components/SubjectHeading/SubjectHeading.jsx
- src/client/styles/components/SubjectHeadings.scss
Changes the central panel on the index page to make it wider. Requires a small change in html structure to keep sort buttons from pushing other items left.
> Central panel width

- src/app/components/Pagination/Pagination.jsx
- src/app/components/SubjectHeading/BibsList.jsx
- src/app/components/SubjectHeading/SubjectHeadingShow.jsx
- src/client/styles/components/LoadingLayer.scss
- src/client/styles/components/SubjectHeadings.scss
Adds pagination to bibs on subject heading show page. Requires https://github.com/NYPL/subject-headings-explorer-poc/pull/88
> Shep bibs pagination

- src/app/components/SubjectHeading/SubjectHeading.jsx
- src/client/styles/components/SubjectHeadings.scss
Sets appropriate cursors for elements
> Shep cursors

- src/app/components/SubjectHeading/Search/AutosuggestItem.jsx
- src/app/components/SubjectHeading/Search/SubjectHeadingSearch.jsx
- src/app/components/SubjectHeading/SubjectHeadingPageWrapper.jsx
- src/app/components/SubjectHeading/SubjectHeadingsContainer.jsx
> Make SubjectHeading/Search folder for search components

- .env-sample
- package-lock.json
- src/app/components/SubjectHeading/BibsList.jsx
- src/app/components/SubjectHeading/SubjectHeadingShow.jsx
- src/server/ApiRoutes/ApiRoutes.js
- src/server/ApiRoutes/Bib.js
- src/server/ApiRoutes/SubjectHeadings.js
Adds server-side endpoint for proxying arbitrary shep-api calls. Also
configures those new endpoints to be used by client-side app.
> Server side shep api proxy

- package-lock.json
- package.json
> Downgrade focustrap to 3.0.3

- src/app/components/SubjectHeading/SubjectHeadingShow.jsx
SCC-1751(https://jira.nypl.org/browse/SCC-1751) requested this change as well
> switch order of righthand content boxes

- src/app/components/Breadcrumbs/Breadcrumbs.jsx
- src/app/components/Item/ItemHoldings.jsx
- src/app/components/SccContainer/SccContainer.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/app/components/SubjectHeading/AdditionalSubjectHeadingsButton.jsx
- src/app/components/SubjectHeading/SortButton.jsx
- src/app/components/SubjectHeading/SubjectHeading.jsx
- src/app/components/SubjectHeading/SubjectHeadingShow.jsx
- src/app/components/SubjectHeading/SubjectHeadingsContainer.jsx
- src/app/components/SubjectHeading/SubjectHeadingsTableHeader.jsx
- src/app/pages/SearchResults.jsx
- src/app/pages/SubjectHeadingsIndex.jsx
- src/client/styles/components/SubjectHeadings.scss
Work in progress PR. SHEP html and classnames are more consistent with the rest of SCC.
> Scc 1755 shep index alignment

- package-lock.json
- package.json
- src/app/components/Application/Application.jsx
- src/app/components/BibPage/AdditionalDetailsViewer.jsx
- src/app/components/BibPage/BibDetails.jsx
- src/app/components/BibPage/BibPage.jsx
- src/app/components/BibPage/DefinitionList.jsx
- src/app/components/BibPage/SubjectHeadings.jsx
- src/app/components/Breadcrumbs/Breadcrumbs.jsx
- src/app/components/Pagination/Pagination.jsx
- src/app/components/SccContainer/SccContainer.jsx
- src/app/components/SearchResultsPage/SearchResultsPage.jsx
- src/app/components/SubjectHeading/AdditionalSubjectHeadingsButton.jsx
- src/app/components/SubjectHeading/BibsList.jsx
- src/app/components/SubjectHeading/PreviewComponents.jsx
- src/app/components/SubjectHeading/Search/AutosuggestItem.jsx
- src/app/components/SubjectHeading/Search/SubjectHeadingSearch.jsx
- src/app/components/SubjectHeading/SubjectHeading.jsx
- src/app/components/SubjectHeading/SubjectHeadingShow.jsx
- src/app/components/SubjectHeading/SubjectHeadingsContainer.jsx
- src/app/components/SubjectHeading/SubjectHeadingsTable.jsx
- src/app/components/SubjectHeading/SubjectHeadingsTableBody.jsx
- src/app/components/SubjectHeading/SubjectHeadingsTableHeader.jsx
- src/app/pages/SearchResults.jsx
- src/app/pages/SubjectHeadingShow.jsx
- src/app/pages/SubjectHeadingsIndex.jsx
I went down a much needed eslint rabbit hole.
> linting new and recently updated files

- src/app/components/SubjectHeading/SubjectHeadingsTableHeader.jsx
> change table heading text

- src/client/styles/components/SubjectHeadings.scss
Some small styling fixes that got broken during merge.
> Add some small styling changes for info boxes

- src/app/components/SubjectHeading/SubjectHeadingShow.jsx
- test/unit/SubjectHeadingShow.test.js
Simplifies unnecessarily complicated logic in `hasUuid` method
> Da/simplify has UUID

- src/app/components/SubjectHeading/SubjectHeading.jsx
- src/client/styles/components/SubjectHeadings.scss
Small highlighting changes, hopefully doesn't intersect too badly with the other refactor work on the subject heading components...
> Fix some minor styling bugs with highlighting

- src/app/components/SubjectHeading/BibsList.jsx
- src/app/components/SubjectHeading/PreviewComponents.jsx
- src/app/components/SubjectHeading/SubjectHeading.jsx
- src/app/components/SubjectHeading/SubjectHeadingShow.jsx
- src/app/components/SubjectHeading/SubjectHeadingsContainer.jsx
- src/app/components/SubjectHeading/SubjectHeadingsTable.jsx
- src/app/components/SubjectHeading/SubjectHeadingsTableBody.jsx
- src/app/components/SubjectHeading/SubjectHeadingsTableHeader.jsx
- src/client/styles/components/SubjectHeadings.scss
This branch merges the changes from `da/nested-table-and-right-alignment` and `sib/style-changes-from-planning`. The latter branch has changes to bring the "Loading titles" back to the show page and makes the empty container a more logical placeholder.
> Loading layer and placeholder for Bibs on show page

- src/app/components/SubjectHeading/SubjectHeadingsContainer.jsx
- src/client/styles/components/SubjectHeadings.scss
Break points for new frontend feature at 757px and 419px. Still room for improvement, but significant improvement.
> Alphabetical pagination

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/app/components/HoldConfirmation/HoldConfirmation.jsx
- src/app/components/HoldRequest/HoldRequest.jsx
This PR includes the package updates from dependabot and the updated `@nypl/design-toolkit`
> Merge changes from `development` into `shep-development`

- src/app/components/Pagination/Pagination.jsx
> Add check for pagination button

- src/app/components/SubjectHeading/BibsList.jsx
- src/server/ApiRoutes/Bib.js
Frontend changes for https://jira.nypl.org/browse/SCC-1813
Also, simplified one Axios call.
> add asc and desc date sort to BibsList

- src/app/components/ShepContainer/ShepContainer.jsx
- src/app/components/SubjectHeading/SubjectHeadingsContainer.jsx
More minimal approach for SCC-1801 https://jira.nypl.org/browse/SCC-1801
> SCC-1801 add loading layer to SHEP index

- src/app/components/SubjectHeading/NestedTableColumnHeading.jsx
One last change needed for switching the columns
> fix column order in nested tables

- src/server/ApiRoutes/Bib.js
This PR fixes and simplifies the logic for conditionally calling SHEP API. The original need for this ticket is that the SHEP API call could not be part of the `Promise.all`, since if the bib has no subject headings or is not in SHEP API, the whole `Promise` would fail.
When SHEP API is working and a bib has subject headings, you will go to SHEP from a bib page. If SHEP API is not working and there are subject heading links, they will go to SearchResults with the  appropriate subject heading literal filter applied. To test this, try with SHEP API running and then not running. 🤞
https://jira.nypl.org/browse/SCC-1763
> bug fix for SCC-1763 Front end error handling for fetching subject headings in bib page

- src/app/components/SubjectHeading/SubjectHeading.jsx
https://jira.nypl.org/browse/SCC-1878
> SCC-1878 / show only last component in show page context box

- src/app/components/SubjectHeading/SubjectHeading.jsx
- src/app/components/SubjectHeading/SubjectHeadingShow.jsx
- src/client/styles/components/SubjectHeadings/SubjectHeadingShow.scss
- src/client/styles/components/SubjectHeadings/SubjectHeadingsTableHeader.scss
More styling for the show page. Mostly alignment in the content of the respective boxes.
> SCC-1829 & SCC-1854 show page tweaks

- src/app/components/SubjectHeading/SubjectHeading.jsx
- src/app/components/SubjectHeading/SubjectHeadingShow.jsx
- src/app/components/SubjectHeading/SubjectHeadingsTableBody.jsx
- src/client/styles/components/SubjectHeadings/SubjectHeadingShow.scss
- src/client/styles/components/SubjectHeadings/SubjectHeadingsTableHeader.scss
This PR fixes the logic for pre-opening the linked index with the context of the `linked` heading.
It also has minor styling tweaks for the show pages and changes the text for the link to the linked index.
> SCC-1829 / linked index feature

- src/app/components/SubjectHeading/Search/SubjectHeadingSearch.jsx
- src/app/components/SubjectHeading/SubjectHeading.jsx
- src/app/components/SubjectHeading/SubjectHeadingsTableBody.jsx
Puts `catch`es for API calls that did not have them before. Also, stumbled upon a use of `prevState` that does not follow convention to avoid manipulating state directly and went ahead and fixed our use of that.
Basic code fixes
Did not add related tests yet. Checked pages that were impacted by re-writing the `setState`s
**Dependencies for merging? Releasing to production?**
None.
**Has the application documentation been updated for these changes?**
Not necessary
Yes, I did.
> SCC-1897 small changes

- src/app/components/SubjectHeading/SubjectHeading.jsx
- src/app/components/SubjectHeading/SubjectHeadingShow.jsx
- src/client/styles/components/SubjectHeadings.scss
- src/client/styles/components/SubjectHeadings/SubjectHeading.scss
- src/client/styles/components/SubjectHeadings/SubjectHeadingShow.scss
This makes sure the correct font width and border styling gets applied to the appropriate subject heading table rows. 
Frontend bugs and mismatches with UX design.
Checkout branch and run locally. If approved, I can try writing a couple unit tests to make sure the correct class names are applied.
Yes.
> SCC-1944 & SCC-1924

- src/app/components/ShepContainer/ShepContainer.jsx
Not sure what happened here. Seems like a mistake?
> Remove extra code from ShepContainer

- src/app/components/ShepContainer/ShepContainer.jsx
The "Skip to main content" link currently does not work. 
https://jira.nypl.org/browse/SCC-2008
> SCC-2008/ Accessibility: Skip to Content
